#!/bin/bash
dirname=WindowsVM
maindir=$HOME/$dirname
imagesdir=/var/lib/libvirt/images
# Downloads VirtIO Drivers if dont exist already
virtio_download() {
  echo -e "\n-- FUNCTION: VirtIO Drivers Download\n" >> $logfile

  if [[ ! -f $maindir/virtio-win.iso && ! -f $imagesdir/virtio-win.iso ]]; then
    echo "-- VirtIO Drivers ISO doesn't exist in $imagesdir" 
    echo "-- Downloading VirtIO Drivers ISO." 
  	sudo wget -cq https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso -O $imagesdir/virtio-win.iso --show-progress --progress=bar
  fi
}
# Check if Windows iso and virtio-drivers exist in ~/$maindir
win10_download() {
	echo "workonthis"
}
  

# Clones the main reporsitory and defining the VM via `virsh`
gitndefine() {
  echo -e "\n-- FUNCTION: Clone Repository and define VM" >> $logfile

  if [[ $distro == "UBUNTU" ]]; then
    distro="DEBIAN"
  fi

  if [[ ! -d $HOME/quick-vm ]]; then
    cd $HOME
    echo "-- Cloning from the repository..." >> $logfile
    git clone --recursive https://github.com/thegamerhat/quick-vm >> $logfile 
  
  else
    cd $HOME/quick-vm
    git pull

  fi

  echo "-- Copying vdisk and essentials to $imagesdir" >> $logfile
  sudo rsync -q $HOME/quick-vm/kvm/Windows10Vanilla.qcow2 $imagesdir/ >> $logfile
  sudo rsync -q $HOME/quick-vm/kvm/essentials.iso $imagesdir/ >> $logfile

  if [[ -f $imagesdir/virtio-win.iso && -f $imagesdir/win10.iso ]]; then
    echo "-- Defining default VM" >> $logfile
    sudo virsh define ~/quick-vm/kvm/$distro/Windows10-default.xml  >> $logfile

    echo "-- Copying OVMF_CODE.fd" >> $logfile
    if [[ $distro == "ARCH" ]]; then
      sudo cp /usr/share/ovmf/x64/OVMF_CODE.fd /var/lib/libvirt/qemu/nvram/Windows10-default_VARS.fd >> $logfile
    elif [[ $distro == "DEBIAN" || $distro == "UBUNTU" ]]; then
      sudo cp /usr/share/OVMF/OVMF_CODE.fd /var/lib/libvirt/qemu/nvram/Windows10-default_VARS.fd  >> $logfile
    elif [[ $distro == "FEDORA" ]]; then
      sudo cp /usr/share/edk2/ovmf/OVMF_CODE.fd /var/lib/libvirt/qemu/nvram/Windows10-default_VARS.fd >> $logfile
    fi

    TEXT="\n ✔ Setup is Finished! Follow the instructions from the Official Project page to get started."; greentext

  else
    TEXT="\n [!] Some files missing from $imagesdir"; redtext
    echo -e "\n Please read the instructions on how and where to place them on the Official GitHub Page.\n"
    TEXT="\n ➜ Quick-VM Official GitHub Page: https://github.com/thegamerhat/quick-vm"; whitetext
  fi

}
