#!/bin/bash
set -e

# source lib
script_fullpath=$(dirname "$(readlink -f "$0")")
[ "$(echo "${script_fullpath}" | grep "/proc/*")" ] && script_fullpath="/tmp"
cd "${script_fullpath}"
if ! . lib 2> /dev/null; then
	wget -q https://raw.githubusercontent.com/dari862/my_linux/main/tempfornow/lib
	if ! . lib 2> /dev/null; then
		echo "Error: Failed to locate lib from ${script_fullpath}" >&2
		exit 1
	fi
fi
##################################################################################
# var
##################################################################################
install_xfce4_panel_now=false
install_polybar_now=false
install_qt5ct_now=false
install_jgmenu_now=false
install_bspwm_now=false
 
extra_apps_2_install=("$@")
for option in "${extra_apps_2_install[@]}";do
	if [[ "$option" = "xfce4_panel" ]];then
		install_xfce4_panel_now=true
	elif [[ "$option" = "polybar" ]];then
		install_polybar_now=true
	elif [[ "$option" = "qt5ct" ]];then
		install_qt5ct_now=true
	elif [[ "$option" = "jgmenu" ]];then
		install_jgmenu_now=true
	elif [[ "$option" = "bspwm" ]];then
		install_bspwm_now=true
	fi
done
apt_noninteractive='sudo DEBIAN_FRONTEND=noninteractive apt-get -y'
List_of_apt_2_install_=()

#######################
## must_install_apps_list
#######################
#must have apps
install_must_have_apps=(jq btop xclip curl cbatticon xprintidle yad git lsb-release rofi picom sudo systemd-timesyncd)
install_must_have_apps2=(psmisc unzip dunst xorg pulseaudio arandr autorandr dbus-x11 pnmixer pavucontrol diodon gparted inxi s-tui dfc htop hwinfo synaptic galternatives xdotool libnotify-bin gnome-keyring ntfs-3g acl bash-completion xinit xdg-user-dirs lm-sensors)
install_cool_apps=(micro)
install_openbox_=(openbox obconf xcape tint2 nitrogen)
install_image_viewer_apps=(viewnior)
install_files_manager_app=(thunar thunar-archive-plugin gvfs gvfs-fuse gvfs-backends file-roller ranger meld baobab)
install_firefox_=(firefox firefox-esr)
install_terminal=(kitty terminator)
install_conky_all_app=(conky-all)
install_if_laptop=(tlp tlp-rdw powertop light upower xserver-xorg-input-synaptics acpi xbacklight xinput wireless-tools)
install_Network_apps=(rfkill network-manager network-manager-gnome)
install_terminal_based_sound_app=(mpd mpc ncmpcpp)
install_text_editer_app=(featherpad evince)
install_mediaplayer_app=(mpv)
install_x_lock_extra=(i3lock i3lock-fancy)
install_lightdm_=(lightdm lightdm-gtk-greeter-settings)
install_fonts=(fonts-noto fonts-droid-fallback fonts-cantarell fonts-liberation fonts-opensymbol fonts-noto-core fonts-noto-mono fonts-inconsolata)
install_themes=(papirus-icon-theme fonts-noto-color-emoji fonts-firacode fonts-font-awesome arc-theme gtk3-nocsd numix-icon-theme paper-icon-theme dmz-cursor-theme)
install_themes_tools=(xsettingsd lxappearance)
install_polkit_apps=(policykit-1 policykit-1-gnome)

# ffmpeg for screen recoding , maim for ac-shots , xsel for files-uploader , wmctrl for style-manager and files-uploader
install_for_scripts=(maim ffmpeg at xsel wmctrl)
install_for_script_bl_reload_gtk23=(python3-xlib)
install_autoinstall_firmware=(isenkram)

#######################
## extra apps
#######################
install_xfce4_panel=(xfce4-panel xfce4-settings xfce4-clipman xfce4-whiskermenu-plugin)
install_polybar=(polybar libnm-dev)
install_qt5ct=(qt5ct qt5-style-kvantum libqt5svg5 qml-module-qtquick-controls)
install_jgmenu=(jgmenu)
install_bspwm=(bspwm sxhkd)

##################################################################################
# function
##################################################################################

apt_install_()
{
	$sudoaptinstall "${List_of_apt_2_install_[@]}"
}

add_2_apt_install_()
{
	localarray=("$@")
	if [ "${localarray[0]}" == "lightdm" ] && [ -f "/etc/X11/default-display-manager" ]; then
		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
		[ "$d_d_m" != "lightdm"  ] && apt-get purge -y "$d_d_m"
	fi
	
	for INDEX in "${localarray[@]}"
	do
		if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
			check_apps_in_cache="$(grep " $INDEX " "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_+=("$INDEX") 
				show_m "${INDEX} added to install apps" 
			else
				[ "${localarray[0]}" != "firefox" ] && show_em "failed ${INDEX}."
			fi
		fi
	done
}

##################################################################################
# main
##################################################################################

sudo timedatectl set-timezone Asia/Kuwait
sudo date -s "$(wget --method=HEAD -qSO- --max-redirect=0 google.com 2>&1 | sed -n 's/^ *Date: *//p')" &>/dev/null

update_and_upgrade

list_of_apps_file_path="$(mktemp "${script_fullpath}"/list_of_apps_.XXXXXXXXXXXX)"
show_m "create_list_of_apps"
apt list 2>/dev/null | awk -F"/" '{print " " $1 " "}' > "${list_of_apps_file_path}"

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	add_2_apt_install_ "${install_if_laptop[@]}"
fi

add_2_apt_install_ "${install_lightdm_[@]}"
add_2_apt_install_ "${install_themes[@]}"
add_2_apt_install_ "${install_terminal[@]}"
add_2_apt_install_ "${install_files_manager_app[@]}"
add_2_apt_install_ "${install_x_lock_extra[@]}"
add_2_apt_install_ "${install_firefox_[@]}"
add_2_apt_install_ "${install_terminal_based_sound_app[@]}"
add_2_apt_install_ "${install_conky_all_app[@]}"
add_2_apt_install_ "${install_text_editer_app[@]}"
add_2_apt_install_ "${install_mediaplayer_app[@]}"
add_2_apt_install_ "${install_openbox_[@]}"
add_2_apt_install_ "${install_fonts[@]}"
add_2_apt_install_ "${install_for_scripts[@]}"
add_2_apt_install_ "${install_for_script_bl_reload_gtk23[@]}"
add_2_apt_install_ "${install_Network_apps[@]}"
add_2_apt_install_ "${install_image_viewer_apps[@]}"
add_2_apt_install_ "${install_must_have_apps[@]}"
add_2_apt_install_ "${install_must_have_apps2[@]}"
add_2_apt_install_ "${install_cool_apps[@]}"
add_2_apt_install_ "${install_polkit_apps[@]}"
add_2_apt_install_ "${install_autoinstall_firmware[@]}"
if [[ "$install_xfce4_panel_now" = true ]];then
	add_2_apt_install_ "${install_xfce4_panel[@]}"
fi
if [[ "$install_polybar_now" = true ]];then
	add_2_apt_install_ "${install_polybar[@]}"
fi
if [[ "$install_qt5ct_now" = true ]];then
	add_2_apt_install_ "${install_qt5ct[@]}"
fi
if [[ "$install_jgmenu_now" = true ]];then
	add_2_apt_install_ "${install_jgmenu[@]}"
fi
if [[ "$install_bspwm_now" = true ]];then
	add_2_apt_install_ "${install_bspwm[@]}"
fi

apt_install_

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	show_m "this is laptop"
	show_m "create envycontrol installtion file."
cat << 'EOF' > /tmp/envycontrol_updater_DmDmDmdMdMdM
	cd "$(mktemp -d)" 
	
	wget -qO- 'https://api.github.com/repos/bayasdev/envycontrol/releases/latest' \
  	| grep '"tarball_url"' \
  	| cut -f2,3 -d':' \
  	| tr -d '"' \
  	| tr -d ',' \
  	| xargs wget -O envycontrol.tar.gz && tar -xvzf envycontrol.tar.gz && mv bayasdev* envycontrol
  	
  	[ -d "/usr/share/DmDmDmdMdMdM/opt/downloaded/envycontrol" ] && sudo rm -rdf "/usr/share/DmDmDmdMdMdM/opt/downloaded/envycontrol"
  	[ ! -d "/usr/share/DmDmDmdMdMdM/opt/downloaded" ] && sudo mkdir -p /usr/share/DmDmDmdMdMdM/opt/downloaded
  	[ ! -d "/usr/share/DmDmDmdMdMdM/opt/git" ] && sudo mkdir -p /usr/share/DmDmDmdMdMdM/opt/git
  	
  	if [ -d envycontrol ];then
  		chmod +x ./envycontrol/envycontrol.py 
  		sudo mv envycontrol "/usr/share/DmDmDmdMdMdM/opt/git/"
  		ln -sf "/usr/share/DmDmDmdMdMdM/opt/downloaded/envycontrol/envycontrol.py" "/usr/share/DmDmDmdMdMdM/bin/bin/envycontrol"
  	fi
EOF
	chmod +x /tmp/envycontrol_updater_DmDmDmdMdMdM
fi

show_m "Configer packages."

if [[ "$install_bspwm_now" = true ]];then
	show_m "adding ${Custom_distro_dir_name}_bspwm to xsessions."
	if [ -z "${Custom_distro_dir_name}" ];then
		echo "var Custom_distro_dir_name is empty"
		exit 1
	fi
	sudo mkdir -p "/usr/share/${Custom_distro_dir_name}/lib/xsessions"
	sudo touch "/usr/share/${Custom_distro_dir_name}/lib/xsessions/${Custom_distro_dir_name}_bspwm.desktop"
	sudo ln -sf "/usr/share/${Custom_distro_dir_name}/lib/xsessions/${Custom_distro_dir_name}_bspwm.desktop" /usr/share/xsessions
	sudo rm -rdf "/usr/share/${Custom_distro_dir_name}"
fi

if command -v mpd >/dev/null
then
	if [[ -n "$(pidof mpd)" ]]; then
		killall -9 mpd
	fi
	sudo systemctl stop mpd.socket
	sudo systemctl stop mpd.service 
	sudo systemctl disable mpd.socket 
	sudo systemctl disable mpd.service
fi

sudo isenkram-autoinstall-firmware || : # to prevent script from exiting "isenkram-autoinstall-firmware contain exit command"
apt_purge_with_error2info "${install_autoinstall_firmware[@]}"

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	show_m "some config"
fi
