#!/bin/bash
set -e

if ! test_if_my_stuff_lib_sourced 2>/dev/null; then
	# source lib
	lib_file_name="my_stuff_lib"
	[[ -z "${temp_path}" ]] && temp_path="/tmp/my_stuff"
	mkdir -p "${temp_path}"
	my_stuff_lib_location="$(find $HOME -type f -name ${lib_file_name} | head -1 || :)"
	if [[ ! -z "${my_stuff_lib_location}" ]];then
		mv "${my_stuff_lib_location}" "${temp_path}"
		source "${temp_path}"/${lib_file_name}
	elif [[ -f "${temp_path}"/${lib_file_name} ]];then
		if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
			echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
			exit 1
		fi
	else
		echo "wget lib file"
		if wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/${lib_file_name} -O "${temp_path}"/${lib_file_name}; then
			if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
				echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
				exit 1
			fi
		else
			echo "Error: Failed to download ${lib_file_name} ."
			exit 1
		fi
	fi
fi

install_GPU_now="${1-}"
list_of_apps_file_path="$(mktemp "${temp_path}"/list_of_apps_.XXXXXXXXXXXX)"

##################################################################################
# function
##################################################################################
create_apt_list(){
	apt list 2>/dev/null > "${list_of_apps_file_path}" 
}

apt_install_(){
	$_SUDO $__install "${List_of_apt_2_install_[@]}"
}

add_2_apt_install_(){
	localarray=("$@")

	for INDEX in "${localarray[@]}"
	do
		if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
			if grep "^${INDEX}/" ${list_of_apps_file_path};then
				List_of_apt_2_install_+=("$INDEX") 
				show_m "${INDEX} added to install apps" 
			fi
		fi
	done
}

create_20_intel_conf_file(){
	show_m "Create 20-intel.conf file."
	if [ "${intel_gpu_exist}" = "true" ];then
	sudo mkdir -p /etc/X11/xorg.conf.d/
sudo bash -c 'cat << EOF > /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
	Identifier  "Intel Graphics"
	Driver      "Intel"
	Option      "AccelMethod"  "sna"
	Option      "TearFree"	"True"
	Option      "Tiling"	"True"
	Option      "SwapbuffersWait" "True"
	#Option      "AccelMethod"  "uxa"
EndSection
EOF'
	fi
}
##################################################################################
# var
##################################################################################
fingerprint_exist=false
List_of_apt_2_install_=()

#######################
## must_install_apps_list
#######################
#must have apps
install_audio=(pulseaudio pavucontrol)
install_if_laptop=(acpi upower)
if [[ "$(ls /sys/class/backlight | head -n 1)" == *"intel_"* ]]; then
	install_if_laptop+=(xbacklight)
else
	install_if_laptop+=(light)
fi
install_fingerprint=(fprintd libpam-fprintd)
install_wireless=(wireless-tools)
install_bluetooth=(bluez blueman)
install_autoinstall_firmware=(isenkram)

if lsusb | grep -i fingerprint >/dev/null || lspci | grep -i fingerprint >/dev/null || ls /sys/bus/usb/devices/* | grep -i fingerprint >/dev/null; then
    fingerprint_exist=true
fi

##################################################################################
# GPU Drivers
##################################################################################
if [[ "${install_GPU_now}" = "install_GPU" ]];then
	if [ "$(lspci | grep "VGA compatible controller" | grep VMware -c)" != "0" ];then
		echo "This is VM"
	else
		if [ "${nvidia_gpu_exist}" = "true" ];then
			_cuda_="${2-}"
			_kernel_open_dkms_="${3-}"
			add_2_apt_install_ "nvidia-driver nvidia-smi nvidia-settings $_kernel_open_dkms_ $_cuda_"
		fi
		
		if [ "${amd_gpu_exist}" = "true" ];then
			add_2_apt_install_ "libgl1-mesa-dri xserver-xorg-video-ati xserver-xorg-video-amdgpu mesa-vulkan-drivers vkbasalt"
		fi
		
		if [ "${intel_gpu_exist}" = "true" ];then
			add_2_apt_install_ "xserver-xorg-video-intel intel-gpu-tools intel-media-va-driver"
		fi
	fi
fi

##################################################################################
# main
##################################################################################
create_apt_list # needed for add_2_apt_install_

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	add_2_apt_install_ "${install_if_laptop[@]}"
fi

if [[ "$fingerprint_exist" = true ]];then
    add_2_apt_install_ "${install_fingerprint[@]}"
fi

if lspci | egrep -i 'wifi|wireless' 1>/dev/null ;then
	add_2_apt_install_ "${install_wireless[@]}"
fi

if sudo dmesg | grep -i bluetooth 1>/dev/null || sudo lsusb | grep -i bluetooth 1>/dev/null ;then
	add_2_apt_install_ "${install_bluetooth[@]}"
fi

add_2_apt_install_ "${install_audio[@]}"
add_2_apt_install_ "${install_Network[@]}"
add_2_apt_install_ "${install_autoinstall_firmware[@]}"

if [[ "${install_GPU_now}" = "install_GPU" ]];then
	if [ "${nvidia_gpu_exist}" = "true" ];then
		if [[ ! -f "/usr/share/keyrings/nvidia-drivers.gpg" ]];then
			curl -fSsL "https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/3bf863cc.pub" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
		fi
		
		if [[ ! -f "/etc/apt/sources.list.d/nvidia-drivers.list" ]];then 
			echo "deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/ /" | sudo tee /etc/apt/sources.list.d/nvidia-drivers.list
		fi
	fi
fi
		
if [ "$this_is_ubuntu" = true ];then
	sudo apt-get install -y software-properties-common
	sudo add-apt-repository -y universe
	sudo add-apt-repository -y multiverse
	show_m "Running Update."
	aptupdate
else
	show_m "Running Update."
	aptupdate
fi
		
apt_install_

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	show_m "this is laptop"
	if [ "$number_of_gpus" -gt 1 ]; then
		show_m "create envycontrol installtion file."
cat << 'EOF' > "${temp_path}"/envycontrol_updater_DmDmDmdMdMdM
	envycontrol_updater_path="$(mktemp -d)" 
	distroname="DmDmDmdMdMdM"
	wget -qO- 'https://api.github.com/repos/bayasdev/envycontrol/releases/latest' \
  	| grep '"tarball_url"' \
  	| cut -f2,3 -d':' \
  	| tr -d '"' \
  	| tr -d ',' \
  	| xargs wget -O "${envycontrol_updater_path}"/envycontrol.tar.gz && tar -xvzf "${envycontrol_updater_path}"/envycontrol.tar.gz -C "${envycontrol_updater_path}" && mv "${envycontrol_updater_path}"/bayasdev* "${envycontrol_updater_path}"/envycontrol
  	
  	[ -d "/usr/share/${distroname}/opt/downloaded/envycontrol" ] && sudo rm -rdf "/usr/share/${distroname}/opt/downloaded/envycontrol"
  	[ ! -d "/usr/share/${distroname}/opt/downloaded" ] && sudo mkdir -p /usr/share/${distroname}/opt/downloaded
  	[ ! -d "/usr/share/${distroname}/opt/git" ] && sudo mkdir -p /usr/share/${distroname}/opt/git
  	
  	if [ -d "${envycontrol_updater_path}"/envycontrol ];then
  		chmod +x "${envycontrol_updater_path}"/envycontrol/envycontrol.py 
  		sudo mv "${envycontrol_updater_path}"/envycontrol "/usr/share/${distroname}/opt/git/"
  		ln -sf "/usr/share/${distroname}/opt/downloaded/envycontrol/envycontrol.py" "/usr/share/${distroname}/bin/bin/envycontrol"
  	fi
EOF
		chmod +x "${temp_path}"/envycontrol_updater_DmDmDmdMdMdM
	fi
fi
show_m "run isenkram-autoinstall-firmware."
sudo isenkram-autoinstall-firmware || : # to prevent script from exiting "isenkram-autoinstall-firmware contain exit command"

show_m "Remove isenkram package."
apt_purge_with_error2info "${install_autoinstall_firmware[@]}"

show_m "Configer packages."

#create_20_intel_conf_file

if [[ "$fingerprint_exist" = true ]];then
	mktemp "${temp_path}"/fingerprint_exist_XXXXXX
fi

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	show_m "some config"
fi

if [[ "${install_GPU_now}" = "install_GPU" ]];then
	mktemp "${temp_path}"/GPU_Drivers_ready_XXXXXX
fi

if command -v fprintd-verify > /dev/null ;then
	sudo pam-auth-update --enable fprintd
fi
