#!/bin/bash
set -e

if ! test_if_my_stuff_lib_sourced 2>/dev/null; then
	# source lib
	lib_file_name="my_stuff_lib"
	[[ -z "${temp_path}" ]] && temp_path="/tmp/my_stuff"
	mkdir -p "${temp_path}"
	my_stuff_lib_location="$(find $HOME -type f -name ${lib_file_name} | head -1 || :)"
	if [[ ! -z "${my_stuff_lib_location}" ]];then
		mv "${my_stuff_lib_location}" "${temp_path}"
		source "${temp_path}"/${lib_file_name}
	elif [[ -f "${temp_path}"/${lib_file_name} ]];then
		if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
			echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
			exit 1
		fi
	else
		echo "wget lib file"
		if wget -q https://raw.githubusercontent.com/dari862/my_stuff_installer/main/tempfornow/${lib_file_name} -O "${temp_path}"/${lib_file_name}; then
			if ! source "${temp_path}"/${lib_file_name} 2> /dev/null; then
				echo "Error: Failed to source ${lib_file_name} from ${temp_path}" >&2
				exit 1
			fi
		else
			echo "Error: Failed to download ${lib_file_name} ."
			exit 1
		fi
	fi
fi

##################################################################################
# var
##################################################################################
install_xfce4_panel_now=false
install_polybar_now=false
install_qt5ct_now=false
install_jgmenu_now=false
install_bspwm_now=false
 
extra_apps_2_install=("$@")
for option in "${extra_apps_2_install[@]}";do
	if [[ "$option" = "xfce4_panel" ]];then
		install_xfce4_panel_now=true
	elif [[ "$option" = "polybar" ]];then
		install_polybar_now=true
	elif [[ "$option" = "qt5ct" ]];then
		install_qt5ct_now=true
	elif [[ "$option" = "jgmenu" ]];then
		install_jgmenu_now=true
	elif [[ "$option" = "bspwm" ]];then
		install_bspwm_now=true
	fi
done

List_of_apt_2_install_=()

##################################################################################
# Functions
##################################################################################

apt_install_()
{
	$_SUDO $__install "${List_of_apt_2_install_[@]}"
}

add_2_apt_install_()
{
	localarray=("$@")
	
	for INDEX in "${localarray[@]}"
	do
		if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
			check_apps_in_cache="$(grep " $INDEX " "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_+=("$INDEX") 
				show_m "${INDEX} added to install apps" 
			else
				[ "${localarray[0]}" != "firefox" ] && show_em "failed ${INDEX}."
			fi
		fi
	done
}

##################################################################################
## must_install_apps_list
##################################################################################
#must have apps
install_must_have_apps=(jq btop xclip curl cbatticon xprintidle yad git lsb-release rofi picom sudo systemd-timesyncd)
install_must_have_apps2=(psmisc unzip dunst xorg arandr autorandr dbus-x11 pnmixer diodon gparted inxi s-tui dfc htop hwinfo synaptic galternatives xdotool libnotify-bin gnome-keyring ntfs-3g acl bash-completion xinit xdg-user-dirs lm-sensors)
install_cool_apps=(micro)
install_openbox_=(openbox obconf xcape tint2 nitrogen)
install_image_viewer_apps=(viewnior)
install_files_manager_app=(thunar thunar-archive-plugin gvfs gvfs-fuse gvfs-backends file-roller ranger meld baobab)
install_firefox_=(firefox firefox-esr)
install_terminal=(kitty terminator)
install_conky_all_app=(conky-all)
install_if_laptop=(tlp tlp-rdw powertop xserver-xorg-input-synaptics xinput)
install_terminal_based_sound_app=(mpd mpc ncmpcpp)
install_text_editer_app=(featherpad evince)
install_mediaplayer_app=(mpv)
install_x_lock_extra=(i3lock i3lock-fancy)
install_fonts=(fonts-noto fonts-droid-fallback fonts-cantarell fonts-liberation fonts-opensymbol fonts-noto-core fonts-noto-mono fonts-inconsolata)
install_themes=(papirus-icon-theme fonts-noto-color-emoji fonts-firacode fonts-font-awesome arc-theme gtk3-nocsd numix-icon-theme paper-icon-theme dmz-cursor-theme)
install_themes_tools=(xsettingsd lxappearance)
install_polkit_apps=(policykit-1 policykit-1-gnome)

# ffmpeg for screen recoding , maim for ac-shots , xsel for files-uploader , wmctrl for style-manager and files-uploader
install_for_scripts=(maim ffmpeg at xsel wmctrl)
install_for_script_bl_reload_gtk23=(python3-xlib)

#######################
## extra apps
#######################
install_xfce4_panel=(xfce4-panel xfce4-settings xfce4-clipman xfce4-whiskermenu-plugin)
install_polybar=(polybar libnm-dev)
install_qt5ct=(qt5ct qt5-style-kvantum libqt5svg5 qml-module-qtquick-controls)
install_jgmenu=(jgmenu)
install_bspwm=(bspwm sxhkd)

##################################################################################
# main
##################################################################################

aptupdate
aptfixer
upgrade_now

list_of_apps_file_path="$(mktemp "${temp_path}"/list_of_apps_.XXXXXXXXXXXX)"
show_m "create_list_of_apps"
apt list 2>/dev/null | awk -F"/" '{print " " $1 " "}' > "${list_of_apps_file_path}"

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	add_2_apt_install_ "${install_if_laptop[@]}"
fi

add_2_apt_install_ "${install_themes[@]}"
add_2_apt_install_ "${install_terminal[@]}"
add_2_apt_install_ "${install_files_manager_app[@]}"
add_2_apt_install_ "${install_x_lock_extra[@]}"
add_2_apt_install_ "${install_firefox_[@]}"
add_2_apt_install_ "${install_terminal_based_sound_app[@]}"
add_2_apt_install_ "${install_conky_all_app[@]}"
add_2_apt_install_ "${install_text_editer_app[@]}"
add_2_apt_install_ "${install_mediaplayer_app[@]}"
add_2_apt_install_ "${install_openbox_[@]}"
add_2_apt_install_ "${install_fonts[@]}"
add_2_apt_install_ "${install_for_scripts[@]}"
add_2_apt_install_ "${install_for_script_bl_reload_gtk23[@]}"
add_2_apt_install_ "${install_image_viewer_apps[@]}"
add_2_apt_install_ "${install_must_have_apps[@]}"
add_2_apt_install_ "${install_must_have_apps2[@]}"
add_2_apt_install_ "${install_cool_apps[@]}"
add_2_apt_install_ "${install_polkit_apps[@]}"
if [[ "$install_xfce4_panel_now" = true ]];then
	add_2_apt_install_ "${install_xfce4_panel[@]}"
fi
if [[ "$install_polybar_now" = true ]];then
	add_2_apt_install_ "${install_polybar[@]}"
fi
if [[ "$install_qt5ct_now" = true ]];then
	add_2_apt_install_ "${install_qt5ct[@]}"
fi
if [[ "$install_jgmenu_now" = true ]];then
	add_2_apt_install_ "${install_jgmenu[@]}"
fi
if [[ "$install_bspwm_now" = true ]];then
	add_2_apt_install_ "${install_bspwm[@]}"
fi

apt_install_

show_m "Configer packages."

if [[ "$install_bspwm_now" = true ]];then
	show_m "adding ${Custom_distro_dir_name}_bspwm to xsessions."
	if [ -z "${Custom_distro_dir_name}" ];then
		echo "var Custom_distro_dir_name is empty"
		exit 1
	fi
	sudo mkdir -p "/usr/share/${Custom_distro_dir_name}/lib/xsessions"
	sudo touch "/usr/share/${Custom_distro_dir_name}/lib/xsessions/${Custom_distro_dir_name}_bspwm.desktop"
	sudo ln -sf "/usr/share/${Custom_distro_dir_name}/lib/xsessions/${Custom_distro_dir_name}_bspwm.desktop" /usr/share/xsessions
	sudo rm -rdf "/usr/share/${Custom_distro_dir_name}"
fi

if command -v mpd >/dev/null
then
	if [[ -n "$(pidof mpd)" ]]; then
		killall -9 mpd
	fi
	sudo systemctl stop mpd.socket
	sudo systemctl stop mpd.service 
	sudo systemctl disable mpd.socket 
	sudo systemctl disable mpd.service
fi

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	show_m "some config"
	if sudo dmesg | grep -i bluetooth 1>/dev/null || sudo lsusb | grep -i bluetooth 1>/dev/null ;then
		[[ -f "/etc/tlp.conf" ]] && sudo sed -i 's/#DEVICES_TO_DISABLE_ON_STARTUP=.*/DEVICES_TO_DISABLE_ON_STARTUP="bluetooth"/g' /etc/tlp.conf
	fi
	sudo systemctl enable tlp
	sudo  tlp start || tlp_error="true"
	if [[ "$tlp_error" == "true" ]];then
		sudo  tlp start | grep '>>> Invoke' >> "${temp_path}"/tlp_error_Invoke
		if [[ -f "${temp_path}/tlp_error_Invoke" ]];then
			sed -i "s/' to correct this.//g" "${temp_path}"/tlp_error_Invoke
			sed -i "s/>>> Invoke '//g" "${temp_path}"/tlp_error_Invoke
			chmod +x "${temp_path}"/tlp_error_Invoke
			sudo bash "${temp_path}"/tlp_error_Invoke
			sudo  tlp start
		fi
		if sudo tlp-stat |  grep '* Install' &>/dev/null ;then
			sudo tlp-stat |  grep '* Install' | awk -F' '  '{print "apt-get install -y " $3}' >> "${temp_path}"/tlp_install_exta_apps
			if [[ -f "${temp_path}/tlp_install_exta_apps" ]];then
				chmod +x "${temp_path}"/tlp_install_exta_apps
				sudo bash "${temp_path}"/tlp_install_exta_apps
			fi
		fi
	fi
fi
