#!/bin/bash
git_clone_Array=(
my_stuff
Theme_Stuff
)

getthis=""
show_m "git clone ${getthis}"
my_stuff_location="$(find $HOME -type d -name ${getthis} | head -1)"

if [[ -z "${my_stuff_location}" ]];then
	my_stuff_location="${temp_path}"
fi

if [ ! -d "${my_stuff_location}/${getthis}" ]; then 
	git clone --depth=1 "https://github.com/dari862/${getthis}.git" "${my_stuff_location}/${getthis}"
else
	show_m "${getthis} Folder does exsist"
fi

getthis=""
show_m "git clone ${getthis}"
Theme_Stuff_location="$(find $HOME -type d -name ${getthis} | head -1)"

if [[ -z "${Theme_Stuff_location}" ]];then
	Theme_Stuff_location="${temp_path}"
fi

if [ ! -d "${Theme_Stuff_location}/${getthis}" ]; then 
	git clone --depth=1 "https://github.com/dari862/${getthis}.git" "${Theme_Stuff_location}/${getthis}"
else
	show_m "${getthis} Folder does exsist"
fi
