#!/bin/sh
#must have apps
install_audio="pulseaudio pavucontrol"
install_drivers_if_laptop="acpi upower"
install_drivers_if_laptop_xbacklight="xbacklight"
install_drivers_if_laptop_light="light"
install_wireless="wireless-tools"
install_bluetooth="bluez blueman"
install_autoinstall_firmware="fwupd"
install_exfat=""
