#!/bin/sh
create_to_be_purged_list(){
	[ -f "${installer_phases}/create_to_be_purged_list" ] && return
		if grep -q pam_wtmpdb.so /etc/pam.d/common-session;then
			sudo sed -i '/^[[:space:]]*session[[:space:]]\+optional[[:space:]]\+pam_wtmpdb\.so/ s/^/# /' /etc/pam.d/common-session
		fi
		
		_purge_it=""
		to_be_purged="aisleriot anthy kasumi aspell debian-reference-common fcitx fcitx-bin fcitx-frontend-gtk2 fcitx-frontend-gtk3 fcitx-mozc five-or-more four-in-a-row gnome-chess gnome-klotski gnome-mahjongg gnome-mines gnome-music gnome-nibbles gnome-robots gnome-sudoku gnome-taquin gnome-tetravex gnote goldendict hamster-applet hdate-applet hexchat hitori iagno khmerconverter lightsoff mate-themes malcontent mlterm mlterm-tiny mozc-utils-gui quadrapassel reportbug rhythmbox scim simple-scan sound-juicer swell-foop tali uim xboard xiterm+thai xterm im-config xfce4-notifyd xfce4-power-manager* "
		#to_be_purged="$to_be_purged python3-debconf apt-listchanges debian-faq doc-debian libpam-wtmpdb wtmpdb manpages python3-debian python3-debianbts inetutils-telnet krb5-locales netcat-traditional python3-reportbug traceroute"

		[ "$remove_aria2" = true ] && show_sm "adding aria2 package to remove list" && aria2="aria2" || aria2=""
		package_installed snap && show_sm "adding snap package to remove list" && snap="snap" || snap=""
		package_installed linuxlibertine && show_sm "adding fonts-linuxlibertine to purging list (fonts-linuxlibertine break polybar) " && linuxlibertine="linuxlibertine" || linuxlibertine=""
		to_be_purged="${to_be_purged} ${install_autoinstall_firmware} ${aria2} ${snap} ${linuxlibertine}"
		for package in ${to_be_purged};do
			if package_installed "$package";then
				_purge_it="$_purge_it $package"
			else
				show_wm_only "$package does not exist"
			fi
		done
		echo "_purge_it=\"$_purge_it\"" >> "${save_value_file}"
	touch "${installer_phases}/create_to_be_purged_list"
}

purge_some_unnecessary_pakages(){
	[ -f "${installer_phases}/purge_some_unnecessary_pakages" ] && return
	show_m "purge some unnecessary pakages"
	create_to_be_purged_list
	if [ "$run_purge_some_unnecessary_pakages" = "Y" ];then
		show_im "purging apps"
		remove_packages "${_purge_it}"
	fi
	run_autoclean
	show_im "removing apt-fast and conf"
	[ -f /usr/local/bin/apt-fast ] && show_sm "removing apt-fast" && $_SUPERUSER rm -f /usr/local/bin/apt-fast
	[ -f /etc/apt-fast.conf ] && show_sm "removing apt-fast.conf" && $_SUPERUSER rm -f /etc/apt-fast.conf
	touch "${installer_phases}/purge_some_unnecessary_pakages"
}

disable_some_unnecessary_services(){
	[ -f "${installer_phases}/disable_some_unnecessary_services" ] && return
	
	if [ "$init_system_are" = "systemd" ];then
		if [ "$run_disable_some_unnecessary_services" = "Y" ];then
			show_m "Disable some unnecessary services"
			
			# INFO: Some boot services included in Debian are unnecesary for most usres (like NetworkManager-wait-online.service, ModemManager.service or pppd-dns.service)
			for service in NetworkManager-wait-online.service ModemManager.service pppd-dns.service;do
				service_manager stop $service
				service_manager mask $service
			done
	
			# Disable tracker (Data indexing for GNOME mostly)
			for service in tracker-store.service tracker-miner-fs.service tracker-miner-rss.service tracker-extract.service tracker-miner-apps.service tracker-writeback.service;do
				service_manager mask $service
			done
			#service_manager mask gvfs-udisks2-volume-monitor.service
			#service_manager mask gvfs-daemon.service
			#service_manager mask gvfs-metadata.service
		fi
	fi
	touch "${installer_phases}/disable_some_unnecessary_services"
}
