#!/bin/bash
# Exit on any error
set -e

# Log messages with timestamps
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
}

# Check if NVIDIA GPU is present
check_nvidia_gpu() {
    lspci | grep -i nvidia > /dev/null
}

# Check if NVIDIA drivers are installed
check_nvidia_driver() {
    dpkg -l | grep -i nvidia-driver > /dev/null
}

# Update apt sources list
update_sources() {
    log_message "Replacing the apt sources list..."
    if [ ! -f ./sources.list ]; then
        log_message "Error: sources.list file not found!"
        exit 1
    fi
    sudo cp ./sources.list /etc/apt/sources.list
    sudo apt update && sudo apt upgrade -y
}

# Install NVIDIA drivers if needed
install_nvidia_driver() {
    if check_nvidia_gpu; then
        log_message "NVIDIA GPU detected."

        if ! check_nvidia_driver; then
            log_message "NVIDIA drivers are not installed. Installing..."
            sudo apt install -y nvidia-driver
        else
            log_message "NVIDIA drivers are already installed."
        fi

        log_message "Configuring NVIDIA..."
        sudo mkdir -p /etc/default /boot/grub

        # Modify GRUB configuration
        log_message "Configuring GRUB for NVIDIA..."
        sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="quiet"/GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=2 nvidia_drm.modeset=1"/' /etc/default/grub
        sudo grub-mkconfig -o /boot/grub/grub.cfg

        # Reboot the system
        log_message "Rebooting system to apply changes..."
        sleep 10
        sudo reboot
    else
        log_message "No NVIDIA GPU detected. Skipping NVIDIA driver installation."
    fi
}

# Install essential dependencies
install_dependencies() {
    log_message "Installing essential dependencies..."
    sudo apt install -y packaging-dev debian-keyring devscripts equivs git
}

# Function to backport a package
backports_build() {
    local package_name="$1"
    if [ -z "$package_name" ]; then
        log_message "Error: Package name is required for backporting."
        exit 1
    fi

    log_message "Starting backport build for package: $package_name"
    local backport_dir="./${package_name}-backports"
    mkdir -p "$backport_dir"
    cd "$backport_dir" || exit 1

    log_message "Fetching source for $package_name from testing..."
    sudo apt source "${package_name}/testing" || { log_message "Failed to fetch source for $package_name."; exit 1; }

    cd "${package_name}"*/ || { log_message "Failed to enter the source directory."; exit 1; }

    log_message "Building the package for $package_name..."
    sudo mk-build-deps --install --remove
    sudo dch --bpo
    sudo dpkg-buildpackage --build=binary --unsigned-changes

    cd ../..
}

# Remove debug symbols from the package directory
backports_remove_dbg() {
    log_message "Removing debug symbols (dbgsym files)..."
    find . -name 'dbgsym' -exec sudo rm -rf {} \;
}

# Build backports for a list of packages
build_backports() {
    local packages=("wayland" "wayland-protocols" "libinput" "libnvidia-egl-wayland1" "swayimg")
    for package in "${packages[@]}"; do
        backports_build "$package"
        backports_remove_dbg
        sudo apt install ./*.deb
    done
}

# Install Hyprland dependencies
install_hyprland_dependencies() {
    log_message "Installing dependencies for Hyprland..."
    local deps=(
        meson wget build-essential ninja-build cmake-extras cmake gettext gettext-base fontconfig
        libfontconfig-dev libffi-dev libxml2-dev libdrm-dev libxkbcommon-x11-dev libxkbregistry-dev
        libxkbcommon-dev libpixman-1-dev libudev-dev libseat-dev seatd libxcb-dri3-dev libvulkan-dev
        libvulkan-volk-dev vulkan-validationlayers-dev libvkfft-dev libgulkan-dev libegl-dev libgles2
        libegl1-mesa-dev glslang-tools libxcb-composite0-dev libavutil-dev libavcodec-dev libavformat-dev
        libxcb-ewmh2 libxcb-ewmh-dev libxcb-present-dev libxcb-icccm4-dev libxcb-render-util0-dev
        libxcb-res0-dev libxcb-xinput-dev jq hwdata libgbm-dev xwayland foot
    )

    for dep in "${deps[@]}"; do
        sudo apt install --no-install-recommends -y "$dep"
    done
}

# Clone and build Hyprland
install_hyprland() {
    log_message "Building Hyprland..."
    sudo rm -rf Hyprland/
    git clone --recursive https://github.com/hyprwm/Hyprland --branch v0.28.0 --single-branch

    sudo rm -rf ~/.config/hypr
    cp -r ./home_dots/.config/hypr ~/.config

    # Apply wlroots patch for NVIDIA and screen sharing
    sed -i 's/glFlush();/glFinish();/g' Hyprland/subprojects/wlroots/render/gles2/renderer.c
    sudo rm Hyprland/subprojects/wlroots/types/output/render.c
    cp -R wlrootspatch/render.c Hyprland/subprojects/wlroots/types/output/

    cd Hyprland/subprojects
    git clone https://gitlab.freedesktop.org/emersion/libdisplay-info --branch 0.1.1 --single-branch
    git clone https://gitlab.freedesktop.org/emersion/libliftoff --branch v0.4.1 --single-branch

    cd ..
    meson build
    ninja -C build
    sudo ninja -C build install

    # Remove conflicting packages
    for pkg in xdg-desktop-portal-gnome xdg-desktop-portal-gtk; do
        sudo apt remove -y "$pkg"
    done

    log_message "Hyprland installation complete!"
}


# Function to install packages
install_packages() {
    sudo apt install --no-install-recommends -y "$@"
}

# Function to clone a Git repository and install from it
clone_and_install() {
    local repo_url=$1
    local branch=$2
    local build_dir=$3

    git clone "$repo_url" --branch "$branch" --single-branch "$build_dir"
    cd "$build_dir"
    make
    sudo make install
    cd ..
    rm -rf "$build_dir"
}

# Function to copy configuration files
copy_configs() {
    cp -r "$1" ~/.local/
}

# Function to set up user directories and update configuration
setup_user_dirs() {
    mkdir -p ~/desktop ~/downloads ~/public ~/docs ~/music ~/pics ~/pics/screenshots ~/pics/wallpaper ~/videos
    cp -r ./wallpaper/my_wallpaper.jpg ~/pics/wallpaper/

    # Setup user directories and locale
    cat <<EOT >> ~/.config/user-dirs.dirs
XDG_DESKTOP_DIR="\$HOME/desktop"
XDG_DOWNLOAD_DIR="\$HOME/downloads"
XDG_TEMPLATES_DIR="\$HOME/templates"
XDG_PUBLICSHARE_DIR="\$HOME/public"
XDG_DOCUMENTS_DIR="\$HOME/docs"
XDG_MUSIC_DIR="\$HOME/music"
XDG_PICTURES_DIR="\$HOME/pics"
XDG_VIDEOS_DIR="\$HOME/videos"
EOT

    cat <<EOT >> ~/.config/user-dirs.locale
en_US.UTF-8
EOT
}

# Function to install a specific application from GitHub
install_from_github() {
    local repo_url=$1
    local branch=$2
    local build_dir=$3
    local install_command=$4

    git clone "$repo_url" --branch "$branch" --single-branch "$build_dir"
    cd "$build_dir"
    eval "$install_command"
    cd ..
    rm -rf "$build_dir"
}

# -----------------------------------------------------------------------------
# Setup functions for individual components
# -----------------------------------------------------------------------------

# Function to set up Neovim
install_neovim() {
    install_packages ripgrep latexmk wl-clipboard python3-pynvim curl
    clone_and_install "https://github.com/neovim/neovim" "v0.9.5" "neovim"
}

# Function to set up MPV
install_mpv() {
    install_packages ffmpeg libavfilter-dev libass-dev libmpv-dev
    clone_and_install "https://github.com/mpv-player/mpv" "v0.37.0" "mpv"
}

# Function to install Waybar
install_waybar() {
    install_packages clang-tidy gobject-introspection libdbusmenu-gtk3-dev libevdev-dev libfmt-dev \
        libgirepository1.0-dev libgtk-3-dev libgtkmm-3.0-dev libinput-dev libjsoncpp-dev \
        libmpdclient-dev libnl-3-dev libnl-genl-3-dev libpulse-dev libsigc++-2.0-dev \
        libwayland-dev scdoc upower libxkbregistry-dev libupower-glib-dev libwireplumber-0.4-dev \
        libsndio-dev libgtk-layer-shell-dev libplayerctl-dev libjack-dev libhdate-dev
    clone_and_install "https://github.com/Alexays/Waybar" "0.10.0" "Waybar"
}

# Function to install yt-dlp
install_yt_dlp() {
    install_packages ffmpeg
    clone_and_install "https://github.com/yt-dlp/yt-dlp" "2024.04.09" "yt-dlp"
}

# Function to install Firefox
install_firefox() {
    curl 'https://download-installer.cdn.mozilla.net/pub/firefox/releases/116.0.2/linux-x86_64/en-US/firefox-116.0.2.tar.bz2' -o firefox.tar.bz2
    tar -xjf firefox.tar.bz2
    mv firefox ~/.local/share/
    rm -f firefox.tar.bz2
    sudo rm ~/.local/share/applications/firefox-stable.desktop

    # Create Firefox desktop entry
    mkdir -p ~/.local/share/applications
    cat <<EOT >> ~/.local/share/applications/firefox-stable.desktop
[Desktop Entry]
Name=Firefox Stable
Comment=Web Browser
Exec=${HOME}/.local/share/firefox/firefox %u
Terminal=false
Type=Application
Icon=${HOME}/.local/share/firefox/browser/chrome/icons/default/default128.png
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;
StartupNotify=true
Actions=Private;
[Desktop Action Private]
Exec=${HOME}/.local/share/firefox/firefox --private-window %u
Name=Open in private mode
EOT
}

setup_system() {
    cd /tmp
    git clone https://github.com/valle314/debian-hyprland.git
    cd debian-hyprland

    # Install dependencies
    install_packages imagemagick

    # User directories setup
    setup_user_dirs

    # Install essential tools
    install_packages udiskie fzf unzip zip tar fd-find ranger scdoc

    # Install Neovim
    install_neovim

    # Install MPV
    install_mpv

    # Install Firefox
    install_firefox

    # Install Waybar
    install_waybar

    # Install yt-dlp
    install_yt_dlp

    # Install screenshot tools
    install_packages grim slurp

    # Setup and install Hyprland related tools
    install_from_github "https://github.com/hyprwm/hyprpaper" "v0.4.0" "hyprpaper" "make all && sudo make install"
    install_from_github "https://github.com/hyprwm/hyprpicker" "v0.1.1" "hyprpicker" "make all && sudo make install"

    # Install additional utilities
    install_packages dunst polkit-kde-agent-1 pavucontrol taskwarrior when

    # Setup user configuration files
    copy_configs ./home_dots

    echo "Setup complete! Please logout or reboot the system."
}


# Main script execution
log_message "Starting system update and upgrade..."
update_sources

install_nvidia_driver
install_dependencies

log_message "Building and installing backports..."
build_backports

install_hyprland_dependencies
install_hyprland

setup_system
log_message "Script completed successfully."
