#!/bin/sh
must_purge="system-config-printer zeitgeist zeitgeist-core"

#######################
## must have apps
#######################
install_ufw_apps="ufw"
install_must_have_apps="jq git plocate htop unzip libnotify"
install_must_have_apps2="psmisc gparted inxi s-tui dfc hwinfo acl lm_sensors ntfs-3g"
install_image_viewer_apps="viewnior imagemagick gtk-murrine-engine"
install_files_manager_support_app="gvfs gvfs-mtp gvfs-afc file-roller baobab avahi"
install_terminal="kitty"
install_if_laptop_apps="tlp tlp-rdw powertop"
install_cli_sound_app="mpd mpc ncmpcpp"
install_MIDI_sound_app="wildmidi timidity"
install_text_editer_app="geany geany-plugins zathura"
install_mediaplayer_app="mpv cava"
install_polkit_apps="polkit polkit-gnome gnome-keyring"
install_fonts="noto-fonts google-droid-sans-mono-fonts cantarell-fonts liberation-fonts opensymbol-fonts noto-fonts noto-fonts-mono inconsolata-fonts"
install_passman="keepassxc"

#firefox
install_firefox_="mozilla-firefox"

# ffmpeg for screen recoding and manymore , at for bl-beepmein
install_for_scripts="ffmpeg at"

#for x11
install_X11_apps="x11-utils xorg-x11-server xorg-x11-driver-input dbus-x11 xorg-x11-xinit xdg-user-dirs xclip xwallpaper xdotool xprintidle"
install_must_have_apps_for_X11="yad rofi picom dunst nsxiv "
install_res_apps_for_X11="arandr"
install_locker_app_for_X11="i3lock"
install_if_laptop_apps_x11="xf86-input-synaptics"
install_conky_all_app="conky"
install_openbox_="openbox obconf xcape tint2"
install_themes_tools_for_X11="xsettingsd lxappearance"
# slop for ac-shots and screen recoding , wmctrl for style-manager and files-uploader
install_for_x11_scripts="slop wmctrl"

#for wayland


#######################
## extra apps
#######################
install_files_manager_thunar="thunar thunar-archive-plugin"
install_files_manager_pcmanfm="pcmanfm"
install_qt5ct="qt5ct qt5-style-kvantum qt5-svg qt5-quickcontrols"
install_zsh="zsh"

#for x11
#install_clipman_manager_for_X11="parcellite"
#install_clipman_manager_for_X11="diodon"
#install_clipman_manager_for_X11="xfce4-clipman"
install_polybar="polybar"
install_apps_for_bspwm="bspwm sxhkd"
install_apps_for_dwm="libX11-devel libXft-devel libXinerama-devel devel_basis"
install_jgmenu="jgmenu"

#for wayland


#######################
## better bash
#######################
install_better_bash="bash bash-completion"

#######################
## better shell
#######################
install_better_shell="tar bat fzf command-not-found thefuck highlight lf"

#######################
## extra
#######################
install_extra_apps="micro multitail ncdu tree meld btop"
