#!/bin/sh
must_purge="system-config-printer zeitgeist zeitgeist-core"

#######################
## must have apps
#######################
install_must_have_apps="libnotify"
install_must_have_apps2="lm_sensors xz"
install_image_viewer_apps="gtk-murrine-engine"
install_files_manager_support_app="gvfs-mtp gvfs-afc avahi"
install_terminal=""
install_if_laptop_apps=""
install_cli_sound_app=""
install_MIDI_sound_app="timidity"
install_text_editer_app=""
install_mediaplayer_app=""
install_polkit_apps=""
install_fonts=""
install_passman=""

#firefox
install_firefox_="mozilla-firefox"

# ffmpeg for screen recoding and manymore , at for bl-beepmein
install_for_scripts1="ffmpeg at"
# python3-pyte for theoops , python3-pyte for pickbg
install_for_scripts2="python3-pyte python3-tk"

#for x11
install_X11_apps="x11-utils xorg-x11-server xorg-x11-driver-input dbus-x11 xorg-x11-xinit xdg-user-dirs xclip xwallpaper xdotool xprintidle"
install_must_have_apps_for_X11=""
install_res_apps_for_X11=""
install_locker_app_for_X11=""
install_if_laptop_apps_x11="xf86-input-synaptics"
install_conky_all_app="conky"
install_openbox_="obconf"
install_themes_tools_for_X11=""
install_for_x11_scripts=""

#for wayland


#######################
## extra apps
#######################
install_files_manager_thunar=""
install_files_manager_pcmanfm=""
install_zsh=""

#for x11
install_polybar=""
install_apps_for_bspwm=""
install_apps_for_dwm="libX11-devel libXft-devel libXinerama-devel devel_basis"
install_jgmenu=""

#for wayland


#######################
## better bash
#######################
install_better_bash=""

#######################
## better shell
#######################
install_better_shell="command-not-found"

#######################
## extra
#######################
install_extra_apps=""
