#!/bin/sh
sh_scripts="$(grep -r "#\!/" -I ~/Desktop/my_stuff | awk -F: '{print $1}')"
script_2_fix=""
for script in ${sh_scripts};do
	if shellcheck -i SC2086 $script | grep "\[" >/dev/null 2>&1;then
		script_2_fix="$script\n$script_2_fix"
	fi
done
if [ -n "$script_2_fix" ];then
	printf "$script_2_fix" > ~/Desktop/script_2_fix
fi
