#!/bin/bash
wal_output_path="$HOME/Desktop/wal_output"
mkdir -p "$wal_output_path"

run_wal(){
	walname="${1:-}"
	contrast="${2:-}"
	cols16="${3:-}"
	saturate="${4:-}"
	lightmode="${5:-}"
	if [ "$contrast" != "dddd" ];then
		contrastval="$contrast"
		contrast="--contrast $contrast"
	else
		contrastval="$contrast"
		contrast=""
	fi
	
	if [ "$cols16" != "dddd" ];then
		cols16val="$cols16"
		cols16="--cols16 $cols16"
	else
		cols16val="$cols16"
		cols16=""
	fi
	
	if [ "$saturate" != "dddd" ];then
		saturateval="--saturate $saturate"
		saturate="--saturate $saturate"
	else
		saturateval="$saturate"
		saturate=""
	fi
	
	if [ "$lightmode" != "dddd" ];then
		lightmodeval="-l"
		lightmode="-l"
	else
		lightmodeval="$lightmode"
		lightmode=""
	fi
	
	palette_extractor_output_file="$wal_output_path/${walname}_${contrastval}_${cols16val}_${saturateval}_${lightmodeval}.json"
	
	python3 palette_extractor.py -i "$HOME/Desktop/Theme_Stuff/my_wallpapers/${walname}" $contrast $cols16 $saturate $lightmode -o "$palette_extractor_output_file"
}

test(){
	wallpaper_name="${1:-}"
	run_wal "${wallpaper_name}" "dddd" "dddd" "dddd" "dddd"
	run_wal "${wallpaper_name}" "1" "dddd" "dddd" "dddd"
	run_wal "${wallpaper_name}" "10" "dddd" "dddd" "dddd"
	run_wal "${wallpaper_name}" "21" "dddd" "dddd" "dddd"
	run_wal "${wallpaper_name}" "dddd" "dddd" "-1" "dddd"
	run_wal "${wallpaper_name}" "dddd" "dddd" "1" "dddd"
	run_wal "${wallpaper_name}" "1" "dddd" "-1" "dddd"
	run_wal "${wallpaper_name}" "10" "dddd" "-1" "dddd"
	run_wal "${wallpaper_name}" "21" "dddd" "-1" "dddd"
	run_wal "${wallpaper_name}" "1" "dddd" "1" "dddd"
	run_wal "${wallpaper_name}" "10" "dddd" "1" "dddd"
	run_wal "${wallpaper_name}" "21" "dddd" "1" "dddd"

	run_wal "${wallpaper_name}" "dddd" "lighten" "dddd" "dddd"
	run_wal "${wallpaper_name}" "1" "lighten" "dddd" "dddd"
	run_wal "${wallpaper_name}" "10" "lighten" "dddd" "dddd"
	run_wal "${wallpaper_name}" "21" "lighten" "dddd" "dddd"
	run_wal "${wallpaper_name}" "dddd" "lighten" "-1" "dddd"
	run_wal "${wallpaper_name}" "dddd" "lighten" "1" "dddd"
	run_wal "${wallpaper_name}" "1" "lighten" "-1" "dddd"
	run_wal "${wallpaper_name}" "10" "lighten" "-1" "dddd"
	run_wal "${wallpaper_name}" "21" "lighten" "-1" "dddd"
	run_wal "${wallpaper_name}" "1" "lighten" "1" "dddd"
	run_wal "${wallpaper_name}" "10" "lighten" "1" "dddd"
	run_wal "${wallpaper_name}" "21" "lighten" "1" "dddd"

	run_wal "${wallpaper_name}" "dddd" "dual" "dddd" "dddd"
	run_wal "${wallpaper_name}" "1" "dual" "dddd" "dddd"
	run_wal "${wallpaper_name}" "10" "dual" "dddd" "dddd"
	run_wal "${wallpaper_name}" "21" "dual" "dddd" "dddd"
	run_wal "${wallpaper_name}" "dddd" "dual" "-1" "dddd"
	run_wal "${wallpaper_name}" "dddd" "dual" "1" "dddd"
	run_wal "${wallpaper_name}" "1" "dual" "-1" "dddd"
	run_wal "${wallpaper_name}" "10" "dual" "-1" "dddd"
	run_wal "${wallpaper_name}" "21" "dual" "-1" "dddd"
	run_wal "${wallpaper_name}" "1" "dual" "1" "dddd"
	run_wal "${wallpaper_name}" "10" "dual" "1" "dddd"
	run_wal "${wallpaper_name}" "21" "dual" "1" "dddd"

	run_wal "${wallpaper_name}" "dddd" "dddd" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "1" "dddd" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "10" "dddd" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "21" "dddd" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "dddd" "dddd" "-1" "xxxx"
	run_wal "${wallpaper_name}" "dddd" "dddd" "1" "xxxx"
	run_wal "${wallpaper_name}" "1" "dddd" "-1" "xxxx"
	run_wal "${wallpaper_name}" "10" "dddd" "-1" "xxxx"
	run_wal "${wallpaper_name}" "21" "dddd" "-1" "xxxx"
	run_wal "${wallpaper_name}" "1" "dddd" "1" "xxxx"
	run_wal "${wallpaper_name}" "10" "dddd" "1" "xxxx"
	run_wal "${wallpaper_name}" "21" "dddd" "1" "xxxx"

	run_wal "${wallpaper_name}" "dddd" "lighten" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "1" "lighten" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "10" "lighten" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "21" "lighten" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "dddd" "lighten" "-1" "xxxx"
	run_wal "${wallpaper_name}" "dddd" "lighten" "1" "xxxx"
	run_wal "${wallpaper_name}" "1" "lighten" "-1" "xxxx"
	run_wal "${wallpaper_name}" "10" "lighten" "-1" "xxxx"
	run_wal "${wallpaper_name}" "21" "lighten" "-1" "xxxx"
	run_wal "${wallpaper_name}" "1" "lighten" "1" "xxxx"
	run_wal "${wallpaper_name}" "10" "lighten" "1" "xxxx"
	run_wal "${wallpaper_name}" "21" "lighten" "1" "xxxx"

	run_wal "${wallpaper_name}" "dddd" "dual" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "1" "dual" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "10" "dual" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "21" "dual" "dddd" "xxxx"
	run_wal "${wallpaper_name}" "dddd" "dual" "-1" "xxxx"
	run_wal "${wallpaper_name}" "dddd" "dual" "1" "xxxx"
	run_wal "${wallpaper_name}" "1" "dual" "-1" "xxxx"
	run_wal "${wallpaper_name}" "10" "dual" "-1" "xxxx"
	run_wal "${wallpaper_name}" "21" "dual" "-1" "xxxx"
	run_wal "${wallpaper_name}" "1" "dual" "1" "xxxx"
	run_wal "${wallpaper_name}" "10" "dual" "1" "xxxx"
	run_wal "${wallpaper_name}" "21" "dual" "1" "xxxx"
}

test "adaptive_wall-01.png"
#run_wal "${wallpaper_name}" "dddd" "dddd" "dddd" "dddd"
