#!/bin/sh
#
# https://www.youtube.com/watch?v=6pUDzv49M68
set -e
sudo apt-get update
# for dwm
sudo apt-get install -y build-essential libx11-dev libxft-dev libxinerama-dev
# extra
sudo apt-get install -y feh fonts-jetbrains-mono python3-pip
#for st
sudo apt-get install libharfbuzz-dev
sudo pip3 install pywal --break-system-packages
mkdir -p /tmp/suckless
cd /tmp/suckless
for repo in dwm dmenu st;do
	git clone https://github.com/umrian/$repo
	cd $repo
	sudo make clean install
	cd ..
done
git clone https://github.com/umrian/dotfiles
cd dotfiles

mv .xinitrc start_dwm
sudo chown root:root start_dwm
sudo chmod +x start_dwm
sudo mv start_dwm /usr/bin
mv wallpapers ~/
feh --bg-fill ~/wallpapers/pepper-carrot.jpg > /dev/null 2>&1
mkdir -p ~/.config/polybar
mkdir -p ~/.config/picom
mv config.ini ~/.config/polybar
mv picom.conf ~/.config/picom
sudo tee /usr/share/xsessions/my_stuff_dwm.desktop << EOF > /dev/null 2>&1
[Desktop Entry]
Name=My Stuff dwm
Comment=Log in to a My Stuff dwm session
Exec=/usr/bin/start_dwm
TryExec=/usr/bin/start_dwm
Icon=openbox
Type=Xsession
EOF
sudo reboot
