#!/bin/sh -e
network_manager_app_from_Files_4_Distros="NetworkManager-1"
packages_to_install=""

##################################
# for rest
##################################
__remove_package="dnf remove -y"

create_package_list(){
	# create list_of_apps file
	if [ ! -f "${list_of_apps_file_path}" ];then
		show_im "Creating package list..."
		dnf list 2>/dev/null > "${list_of_apps_file_path}"
	fi
	
	if [ ! -f "${list_of_installed_apps_file_path}" ];then
		show_im "Creating installed package list..."
		rpm -qa 2>/dev/null > "${list_of_installed_apps_file_path}" 
	fi
}

install_packages(){
	check_before_install=false
	packages_to_install="${1:-}"
	if [ -n "$packages_to_install" ];then
		if package_installed "${packages_to_install}";then
			return
		fi
	else
		check_before_install=true
		packages_to_install="${all_Packages_to_install}"
	fi

	if [ -n "${packages_to_install}" ];then
    	(dnf install -y ${packages_to_install} && kill_package_ dnf) || \
		(dnf install -y ${packages_to_install} && kill_package_ dnf) || \
		dnf install -y ${packages_to_install}
    else
    	show_wm_only "all_Packages_to_install are empty"
    	return
    fi
    
    if [ "${check_before_install}" = true ];then
    	failed_2_install=""
    	create_package_list
    	for package in ${packages_to_install};do
    		if ! package_installed "${package}";then
    			failed_2_add_pakage "${package} does not exist."
    		else
    			List_of_installed_packages_="${List_of_installed_packages_} ${package}"
    		fi
    	done
    	failed_2_add_pakage "${INDEX} does not exist."
    fi
}

install_packages_for_dev(){
	failed_to_locate=""
	all_packages_to_install=""
	for package in $@;do
		if dnf search $package >/dev/null 2>&1;then
			all_packages_to_install="$all_packages_to_install $package"
		else
			failed_to_install="$failed_to_install $package"
		fi
	done
	(dnf install -y ${all_packages_to_install} && kill_package_ dnf) || \
	(dnf install -y ${all_packages_to_install} && kill_package_ dnf) || \
	dnf install -y ${all_packages_to_install}
}

add_packages_2_install_list(){
	localarray="$@"
	for INDEX in ${localarray};do
		if ! package_installed "${INDEX}";then
			if grep -q "^$INDEX" "${list_of_apps_file_path}";then
				all_Packages_to_install="$all_Packages_to_install $INDEX"
				show_im "${INDEX} added to install apps" 
			else
				failed_2_add_pakage "${INDEX} does not exist." 
			fi
		fi
	done
}

upgrade_now()
{
	dnf upgrade -y
	dnf update -y
}

remove_packages()
{
	packages="$@"
	if [ -n "$packages" ];then
		show_im "Removing ${packages}."
		${__remove_package} "$package"
	else
		show_wm_only "no packages to remove."
	fi
}

run_autoclean(){
	show_im "run autoremove autoclean."
	dnf clean all
	dnf autoremove -y
}

run_package_manager_autoclean(){
	show_im "autoremove unwanted pakages"
	run_autoclean       
    if [ -d /var/tmp ]; then
        find /var/tmp -type f -atime +5 -delete
    fi
    
    if [ -d /var/log ]; then
        find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
    fi
	if [ "$init_system_are" = "systemd" ]; then
        journalctl --vacuum-time=3d
    fi
}

_unattended_upgrades_()
{
	:
}

install_lightdm_now(){
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	add_packages_2_install_list "${install_lightdm_}"
}

switch_lightdm_now(){
	[ -f "${installer_phases}/switch_lightdm_now" ] && return

	show_im "Switching to ( lightdm )."
	d_d_m="$(basename "$(readlink /etc/systemd/system/display-manager.service)")"
	if ! echo "$d_d_m" | grep -q "lightdm" ;then
		lightdm_does_not_exist=true
	fi
	
	if [ "$lightdm_does_not_exist" = true  ];then
		service_manager disable "$d_d_m" || :
		service_manager enable-only lightdm || :
	else
		show_im "lightdm already exist."
	fi
	touch "${installer_phases}/switch_lightdm_now"
}

enable_rpmfusion_repo(){
	dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
}

package_installed(){
	package="${1:-}"
	if grep -q "^$package " "$list_of_installed_apps_file_path";then
		return 0
	else
		return 1
	fi
}

must_install_apps()
{
	[ -f "${installer_phases}/must_install_apps" ] && return
	show_m "installing req apps"
	install_packages "git"
	touch "${installer_phases}/must_install_apps"
}

pre_package_manager_(){
	[ -f "${installer_phases}/pre_package_manager_" ] && return
	kill_package_ dnf
	upgrade_now
	#enable_rpmfusion_repo
	touch "${installer_phases}/pre_package_manager_"
}

enable_repo() {
  REPO_ID="${1:-}"
  dnf install -y --non-interactive addrepo -f ${REPO_ID}
  dnf install -y --non-interactive --gpg-auto-import-keys refresh
}

install_aur_and_all_needed_packages(){   :; }
