#!/bin/sh -e
network_manager_app_from_Files_4_Distros="NetworkManager-1"

##################################
# for rest
##################################
__remove_package="$_SUPERUSER ${PACKAGER} remove -y"

create_package_list(){
	# create list_of_apps file
	if [ ! -f "${list_of_apps_file_path}" ];then
		show_im "Creating package list..."
		$_SUPERUSER ${PACKAGER} se 2>/dev/null | awk -F'|' '{print $2}' | sed 's/^ //g' > "${list_of_apps_file_path}" 
	fi
	
	if [ ! -f "${list_of_installed_apps_file_path}" ];then
		show_im "Creating installed package list..."
		rpm -qa 2>/dev/null > "${list_of_installed_apps_file_path}" 
	fi
}

install_packages(){
	packages_to_install="${1:-${List_of_apt_2_install_}}"
	if [ -n "${packages_to_install}" ];then
    	($_SUPERUSER ${PACKAGER} install -y ${packages_to_install} && kill_package_ ${PACKAGER}) || \
		($_SUPERUSER ${PACKAGER} install -y ${packages_to_install} && kill_package_ ${PACKAGER}) || \
		$_SUPERUSER ${PACKAGER} install -y ${packages_to_install}
    else
    	show_wm_only "packages_to_install are empty"
    	sleep 1
    fi
}

install_single_package(){
	single_package="${1:-}"
	if [ -n "${single_package}" ];then
    	($_SUPERUSER ${PACKAGER} install -y ${single_package} && kill_package_ ${PACKAGER}) || \
		($_SUPERUSER ${PACKAGER} install -y ${single_package} && kill_package_ ${PACKAGER}) || \
		$_SUPERUSER ${PACKAGER} install -y ${single_package}
    else
    	show_wm "faile to install $single_package"
    	sleep 1
    fi
}

add_packages_2_install_list(){
	localarray="$@"
	for INDEX in ${localarray};do
		if ! package_installed "${INDEX}";then
			if grep -q "^$INDEX" "${list_of_apps_file_path}";then
				packages_to_install="$packages_to_install $INDEX"
				show_im "${INDEX} added to install apps" 
			else
				show_filed_2_add_pakage_m "${INDEX} does not exist." 
			fi
		fi
	done
}
	
upgrade_now()
{
	$_SUPERUSER ${PACKAGER} refresh
	$_SUPERUSER ${PACKAGER} update -y
}

remove_packages()
{
	packages="$@"
	if [ -n "$packages" ];then
		show_im "Removing ${packages}."
		$_SUPERUSER ${__remove_package} $packages
	else
		show_wm_only "no packages to remove."
	fi
}

run_autoclean(){
	show_im "run autoremove autoclean."
	$_SUPERUSER zypper clean -a
	$_SUPERUSER zypper tidy
	$_SUPERUSER zypper cc -a
}

run_package_manager_autoclean(){
	show_im "autoremove unwanted pakages"
	run_autoclean
    if [ -d /var/tmp ]; then
        $_SUPERUSER find /var/tmp -type f -atime +5 -delete
    fi
    
    if [ -d /var/log ]; then
        $_SUPERUSER find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
    fi
	if [ "$init_system_are" = "systemd" ]; then
        $_SUPERUSER journalctl --vacuum-time=3d
    fi
}

_unattended_upgrades_()
{
	case "$1" in
		start)
			[ -f "${installer_phases}/_unattended_upgrades_start" ] && return
			show_im "Starting unattended upgrades (zypper cron setup needed)."
			$_SUPERUSER systemctl enable --now packagekit-background.timer
			touch "${installer_phases}/_unattended_upgrades_start"
		;;
		stop)
			[ -f "${installer_phases}/_unattended_upgrades_stop" ] && return
			show_im "Stopping unattended upgrades."
			$_SUPERUSER systemctl disable --now packagekit-background.timer
			touch "${installer_phases}/_unattended_upgrades_stop"
		;;
	esac
}

install_lightdm_now(){
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	add_packages_2_install_list "${install_lightdm_}"
}

switch_lightdm_now(){
	[ -f "${installer_phases}/switch_lightdm_now" ] && return
	touch "${installer_phases}/switch_lightdm_now"
}

package_installed(){
	package="${1:-}"
	if grep -q "^$package" "$list_of_installed_apps_file_path";then
		return 0
	else
		return 1
	fi
}

pre_package_manager_(){
	[ -f "${installer_phases}/pre_package_manager_" ] && return
	kill_package_ ${PACKAGER}
	upgrade_now
	touch "${installer_phases}/pre_package_manager_"
}
