#!/bin/sh -e
network_manager_app_from_Files_4_Distros="NetworkManager-1"

##################################
# for rest
##################################
__remove_package="zypper remove -y"

create_package_list(){
	# create list_of_apps file
	if [ ! -f "${list_of_apps_file_path}" ];then
		show_im "Creating package list..."
		zypper se 2>/dev/null | awk -F'|' '{print $2}' | sed 's/^ //g' > "${list_of_apps_file_path}" 
	fi
	
	if [ ! -f "${list_of_installed_apps_file_path}" ];then
		show_im "Creating installed package list..."
		rpm -qa 2>/dev/null > "${list_of_installed_apps_file_path}" 
	fi
}

install_packages(){
	packages_to_install="${1:-}"
	if [ -n "$packages_to_install" ];then
		if package_installed "${packages_to_install}";then
			return
		fi
	else
		packages_to_install="${all_Packages_to_install}"
	fi
	List_of_installed_packages_="${List_of_installed_packages_} ${packages_to_install}"
	if [ -n "${packages_to_install}" ];then
    	(zypper install -y ${packages_to_install} && kill_package_ zypper) || \
		(zypper install -y ${packages_to_install} && kill_package_ zypper) || \
		zypper install -y ${packages_to_install}
    else
    	show_wm_only "all_Packages_to_install are empty"
    	return
    fi
}

install_packages_for_dev(){
	failed_to_locate=""
	all_packages_to_install=""
	for package in $@;do
		if zypper search $package >/dev/null 2>&1;then
			all_packages_to_install="$all_packages_to_install $package"
		else
			failed_to_install="$failed_to_install $package"
		fi
	done
	(zypper install -y ${all_packages_to_install} && kill_package_ zypper) || \
	(zypper install -y ${all_packages_to_install} && kill_package_ zypper) || \
	zypper install -y ${all_packages_to_install}
}

add_packages_2_install_list(){
	localarray="$@"
	for INDEX in ${localarray};do
		if ! package_installed "${INDEX}";then
			if grep -q "^$INDEX" "${list_of_apps_file_path}";then
				all_Packages_to_install="$all_Packages_to_install $INDEX"
				show_im "${INDEX} added to install apps" 
			else
				show_filed_2_add_pakage_m "${INDEX} does not exist." 
			fi
		fi
	done
}
	
upgrade_now()
{
	zypper refresh
	zypper update -y
}

remove_packages()
{
	packages="$@"
	if [ -n "$packages" ];then
		show_im "Removing ${packages}."
		${__remove_package} $packages
	else
		show_wm_only "no packages to remove."
	fi
}

run_autoclean(){
	show_im "run autoremove autoclean."
	zypper clean -a
	zypper tidy
	zypper cc -a
}

run_package_manager_autoclean(){
	show_im "autoremove unwanted pakages"
	run_autoclean
    if [ -d /var/tmp ]; then
        find /var/tmp -type f -atime +5 -delete
    fi
    
    if [ -d /var/log ]; then
        find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
    fi
	if [ "$init_system_are" = "systemd" ]; then
        journalctl --vacuum-time=3d
    fi
}

_unattended_upgrades_()
{
	case "$1" in
		start)
			[ -f "${installer_phases}/_unattended_upgrades_start" ] && return
			show_im "Starting unattended upgrades (zypper cron setup needed)."
			systemctl enable --now packagekit-background.timer
			touch "${installer_phases}/_unattended_upgrades_start"
		;;
		stop)
			[ -f "${installer_phases}/_unattended_upgrades_stop" ] && return
			show_im "Stopping unattended upgrades."
			systemctl disable --now packagekit-background.timer
			touch "${installer_phases}/_unattended_upgrades_stop"
		;;
	esac
}

install_lightdm_now(){
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	add_packages_2_install_list "${install_lightdm_}"
}

switch_lightdm_now(){
	[ -f "${installer_phases}/switch_lightdm_now" ] && return
	touch "${installer_phases}/switch_lightdm_now"
}

package_installed(){
	package="${1:-}"
	if grep -q "^$package " "$list_of_installed_apps_file_path";then
		return 0
	else
		return 1
	fi
}

must_install_apps()
{
	[ -f "${installer_phases}/must_install_apps" ] && return
	show_m "installing req apps"
	install_packages "git"
	touch "${installer_phases}/must_install_apps"
}

pre_package_manager_(){
	[ -f "${installer_phases}/pre_package_manager_" ] && return
	kill_package_ zypper
	upgrade_now
	touch "${installer_phases}/pre_package_manager_"
}

enable_repo() {
  REPO_ID="${1:-}"
  if [ "$(zypper repolist enabled 2>/dev/null | grep -c "$REPO_ID")" -le 0 ]; then
    show_im "$REPO_ID repository is not enabled. Enabling now..."
    zypper config-manager --set-enabled "$REPO_ID"
    zypper makecache
    if [ "$(zypper repolist enabled 2>/dev/null | grep -c "$REPO_ID")" -le 0 ]; then
      show_wm "Failed to enable $REPO_ID repository..."
    fi
  fi
}

install_aur_and_all_needed_packages(){   :; }
