#!/bin/sh
must_purge="system-config-printer zeitgeist zeitgeist-core"

#######################
## must have apps
#######################
install_ufw_apps="ufw"
install_must_have_apps="jq git plocate htop unzip libnotify-bin xdg-user-dirs"
install_must_have_apps2="psmisc gparted inxi s-tui dfc hwinfo synaptic galternatives acl lm-sensors ntfs-3g"
install_audio_tray_app="pnmixer"
install_image_viewer_apps="viewnior imagemagick"
install_files_manager_support_app="gvfs gvfs-fuse gvfs-backends file-roller baobab avahi-utils"
install_terminal="kitty"
install_if_laptop_apps="tlp tlp-rdw powertop"
install_cli_sound_app="mpd mpc ncmpcpp"
install_MIDI_sound_app="wildmidi timidity"
install_text_editer_app="geany geany-plugins zathura"
install_mediaplayer_app="mpv cava"
install_polkit_apps="policykit-1 policykit-1-gnome gnome-keyring"
install_fonts="fonts-noto fonts-droid-fallback fonts-cantarell fonts-liberation fonts-opensymbol fonts-noto-core fonts-noto-mono fonts-inconsolata"
install_passman="keepassxc"

#firefox
install_firefox_="firefox-esr"

# ffmpeg for screen recoding and manymore , at for bl-beepmein
install_for_scripts="ffmpeg at"

#for x11
install_X11_apps="x11-utils xorg xserver-xorg-input-all xinput dbus-x11 xinit x11-xserver-utils xclip xwallpaper xdotool xprintidle"
install_must_have_apps_for_X11="yad rofi picom dunst nsxiv "
install_res_apps_for_X11="arandr autorandr"
install_locker_app_for_X11="i3lock"
install_if_laptop_apps_x11="xserver-xorg-input-synaptics"
install_conky_all_app="conky-all"
install_openbox_="openbox obconf xcape tint2"
install_themes_tools_for_X11="xsettingsd lxappearance"
# slop for ac-shots and screen recoding , wmctrl for style-manager and files-uploader
install_for_x11_scripts="slop wmctrl"

#for wayland


#######################
## extra apps
#######################
install_files_manager_thunar="thunar thunar-archive-plugin thunar-volman"
install_files_manager_pcmanfm="pcmanfm"
install_qt5ct="qt5ct qt5-style-kvantum libqt5svg5 qml-module-qtquick-controls"
install_zsh="zsh"

#for x11
#install_clipman_manager_for_X11="parcellite"
#install_clipman_manager_for_X11="diodon"
#install_clipman_manager_for_X11="xfce4-clipman"
install_polybar="polybar libnm-dev"
install_apps_for_bspwm="bspwm sxhkd"
install_apps_for_dwm="build-essential libx11-dev libxft-dev libxinerama-dev"
install_jgmenu="jgmenu"

#for wayland


#######################
## better bash
#######################
install_better_bash="bash bash-completion"

#######################
## better shell
#######################
install_better_shell="tar bat fzf command-not-found thefuck highlight lf"

#######################
## extra
#######################
install_extra_apps="micro multitail ncdu tree dos2unix meld btop"
