#!/bin/sh
if [ "$init_system_are" = "systemd" ];then
	init_manager(){
		_command="${1-}"
		_file="${2-}"
		if [ "${_command}" = "stop" ];then
			$_SUPERUSER systemctl stop ${_file} || show_wm_only "failed to stop ${_file}"
		elif [ "${_command}" = "enable-only" ];then
			$_SUPERUSER systemctl enable ${_file} || show_wm "failed to enable ${_file}"
		elif [ "${_command}" = "enable" ];then
			$_SUPERUSER systemctl enable --now ${_file} || show_wm "failed to start and enable ${_file}"
		elif [ "${_command}" = "disable" ];then
			$_SUPERUSER systemctl disable ${_file} || show_wm_only "failed to disable ${_file}"
		elif [ "${_command}" = "disable-stop" ];then
			$_SUPERUSER systemctl disable ${_file} || show_wm_only "failed to disable ${_file}"
			$_SUPERUSER systemctl stop ${_file} || show_wm_only "failed to stop ${_file}"
		elif [ "${_command}" = "status" ];then
			$_SUPERUSER systemctl is-enabled --quiet ${_file} && $_SUPERUSER systemctl is-active --quiet ${_file} || show_wm "failed to show status of ${_file}"
		elif [ "${_command}" = "mask" ];then
			$_SUPERUSER systemctl mask ${_file} || show_wm "failed to mask ${_file}"
		fi
	}
elif [ "$init_system_are" = "openrc" ];then
	init_manager(){
		_command="${1-}"
		_file="${2-}"
		if [ "${_command}" = "stop" ];then
			$_SUPERUSER rc-service ${_file} stop || show_wm_only "failed to stop ${_file}"
		elif [ "${_command}" = "enable-only" ];then
			$_SUPERUSER rc-update add ${_file} || show_wm "failed to enable ${_file}"
		elif [ "${_command}" = "enable" ];then
			$_SUPERUSER rc-update add ${_file} || show_wm "failed to enable and start ${_file}"
		elif [ "${_command}" = "disable" ];then
			$_SUPERUSER rc-update del ${_file} || show_wm_only "failed to disable ${_file}"
		elif [ "${_command}" = "disable-stop" ];then
			$_SUPERUSER rc-update del ${_file} || show_wm_only "failed to disable ${_file}"
			$_SUPERUSER rc-service ${_file} stop || show_wm_only "failed to stop ${_file}"
		elif [ "${_command}" = "status" ];then
			$_SUPERUSER rc-service ${_file} status --quiet || show_wm "failed to show status of ${_file}"
		elif [ "${_command}" = "mask" ];then
			$_SUPERUSER rc-update del ${_file} || show_wm "failed to mask ${_file}"
		fi
	}
else
	show_em "init_system_are = $init_system_are . $init_system_are does not exist."
fi
