#!/bin/bash
set -e
__noninteractive=""
__noninteractive_install=''
__install=""
__purge=""

set_install_and_purge_var(){
	__noninteractive="DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true"
	__noninteractive_install='$_SUDO DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq'
	__install="$_SUDO ${PACKAGER} install -yq"
	__purge="$_SUDO ${PACKAGER} purge -y"
}

# functions
create_package_list(){
	# create list_of_apps file
	if [[ ! -f "${list_of_apps_file_path}" ]];then
		show_m "create_list_of_apps"
		apt list 2>/dev/null > "${list_of_apps_file_path}" 
	fi
}
set_install_and_purge_var
create_package_list
