#!/bin/bash
set -e
__install="$_SUDO ${PACKAGER} install -yq"

# functions
create_package_list(){
	# create list_of_apps file
	if [[ ! -f "${list_of_apps_file_path}" ]];then
		show_m "create_list_of_apps"
		apt list 2>/dev/null > "${list_of_apps_file_path}" 
	fi
}

create_package_list
