#!/bin/sh
pre_disto_Drivers_installer(){
	. "${prompt_to_install_value_file}"
	show_im "Adding needed Drivers to install list."
	
	add_packages_2_install_list "${install_exfat} ${install_common_exfat}"
	
	new_install_drivers_if_laptop="${install_drivers_if_laptop} ${install_common_drivers_if_laptop}"

	##################################################################################
	# main
	##################################################################################
	if [ "$machine_type_are" = "laptop" ];then
		add_packages_2_install_list "${new_install_drivers_if_laptop}"
	fi

	if lspci | grep -qEi 'wifi|wireless' ;then
		add_packages_2_install_list "${install_wireless} ${install_common_wireless}"
	fi
	
	if [ "$has_bluetooth" = true ];then
		add_packages_2_install_list "${install_bluetooth} ${install_common_bluetooth}"
	fi
	
	if ! package_installed "pipewire" ;then
		add_packages_2_install_list "${install_audio} ${install_common_audio}"
	fi
	
	add_packages_2_install_list "${install_Network} ${install_common_Network}"
	add_packages_2_install_list "${install_autoinstall_firmware} ${install_common_autoinstall_firmware}"
}

post_disto_Drivers_installer(){
	. "${prompt_to_install_value_file}"
	show_im "Configer Drivers."
	if [ -f "/usr/sbin/isenkram-autoinstall-firmware" ];then
		show_im "run isenkram-autoinstall-firmware."
		isenkram-autoinstall-firmware || : # to prevent script from exiting "isenkram-autoinstall-firmware contain exit command"
	fi
	show_im "Configer packages."

	if [ "$machine_type_are" = "laptop" ];then
		show_im "some config"
	fi

	if command_exist fprintd-verify && command_exist pam-auth-update;then
		pam-auth-update --enable fprintd
	fi
	
	touch "${installer_phases}/disto_Drivers_installer"
}
