#!/bin/bash
set -e
__noninteractive=""
__noninteractive_install=''
__install=""
__purge=""

set_install_and_purge_var(){
	__noninteractive="DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true"
	__noninteractive_install='$_SUDO DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true ${PACKAGER} install -yq'
	__install="$_SUDO ${PACKAGER} install -yq"
	__purge="$_SUDO ${PACKAGER} purge -y"
}

create_package_list(){
	# create list_of_apps file
	if [[ ! -f "${list_of_apps_file_path}" ]];then
		show_m "create_list_of_apps"
		apt list 2>/dev/null > "${list_of_apps_file_path}" 
	fi
}

install_packages(){
	($__install "${List_of_apt_2_install_[@]}" && kill_PACKAGE_MANAGER) || ($__install "${List_of_apt_2_install_[@]}" && kill_PACKAGE_MANAGER) || $__install "${List_of_apt_2_install_[@]}"
}

check_if_package_exist_in_repo(){
	local package_name="${1-}"
	if ! dpkg -s "${package_name}" > /dev/null 2>&1; then
		check_apps_in_cache="$(grep "^$package_name/" "${list_of_apps_file_path}" 2>/dev/null || :)"
		if [ -n "${check_apps_in_cache}" ];then
			echo "${package_name}" 
		fi
	fi
}

add_packages_2_install_list()
{
	localarray=("$@")
	
	for INDEX in "${localarray[@]}"
	do
		if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
			check_apps_in_cache="$(grep "^$INDEX/" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_+=("$INDEX") 
				show_m "${INDEX} added to install apps" 
			fi
		fi
	done
}
aptupdate(){
	show_m "updating your system"
	[ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ] || $_SUDO ${PACKAGER} update
}

aptfixer(){
		if ! command -v sudo >/dev/null
		then
			if grep 'deb cdrom' /etc/apt/sources.list;then
				sed -i '/deb cdrom/d' /etc/apt/sources.list
			fi
		else
			if grep 'deb cdrom' /etc/apt/sources.list;then
				$_SUDO sed -i '/deb cdrom/d' /etc/apt/sources.list
			fi
		fi
		aptupdate
		### Fix broken packages for good measure (why not?)
		$__install -f 2>/dev/null || show_em "failed to $__install -f"
}	
	
kill_PACKAGE_MANAGER(){
	$_SUDO killall -9 apt &>/dev/null || $_SUDO killall -9 ${PACKAGER} &>/dev/null || :
}
	
upgrade_now()
{
	$_SUDO ${__noninteractive} ${PACKAGER} -y upgrade
	$_SUDO ${__noninteractive} ${PACKAGER} -y full-upgrade
}
enable_repo_contrib(){
(
IFS=$'\n'
	for l in $deb_lines_contrib; do
		$_SUDO sed -i "s\\^$l$\\$l contrib\\" /etc/apt/sources.list
	done
)
}
enable_repo_nonfree_firmware(){
(
IFS=$'\n'
	for l in $deb_lines_nonfree_firmware; do
		$_SUDO sed -i "s\\^$l$\\$l nonfreefirmware\\" /etc/apt/sources.list
	done
	$_SUDO sed -i 's/nonfreefirmware/non-free-firmware/g'  /etc/apt/sources.list
)
}
enable_repo_nonfree(){
(
IFS=$'\n'
	for l in $deb_lines_nonfree; do
		$_SUDO sed -i "s\\^$l$\\$l nonfreeonly\\" /etc/apt/sources.list
	done
	$_SUDO sed -i 's/nonfreeonly/non-free/g'  /etc/apt/sources.list
)
}
enable_repo_(){
	local update_now=false
	if [[ "$enable_contrib" = true ]];then
		enable_repo_contrib && update_now=true
	fi
	if [[ "$enable_nonfree_firmware" = true ]];then
		enable_repo_nonfree_firmware && update_now=true
	fi
	if [[ "$enable_nonfree" = true ]];then
		enable_repo_nonfree && update_now=true
	fi
}
set_install_and_purge_var
aptfixer
upgrade_now
enable_repo_
create_package_list
