#!/bin/sh
set -e

##################################
# for rest
##################################

install_lightdm_now(){
	[ -f "${installer_phases}/install_lightdm_now" ] && return
	
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	show_im "installing ( lightdm )."
	if [ -f "/etc/X11/default-display-manager" ];then
		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
		[ "$d_d_m" != "lightdm"  ] && lightdm_does_not_exist=true
	else
		lightdm_does_not_exist=true
	fi
	
	if [ "$lightdm_does_not_exist" = true  ];then
		show_im "Install ${install_lightdm_} ."
		add_packages_2_install_list "${install_lightdm_}"
		kill_package_ ${PACKAGER} && install_packages || (kill_package_ ${PACKAGER} && install_packages) || (show_em "failed to install lightdm")
		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1
		$_SUPERUSER dpkg-reconfigure lightdm
	else
		show_im "lightdm already exist."
	fi
	touch "${installer_phases}/install_lightdm_now"
}

create_package_list(){
	# create list_of_apps file
	if [ ! -f "${list_of_apps_file_path}" ];then
		show_im "create_list_of_apps"
		${PACKAGER} list 2>/dev/null > "${list_of_apps_file_path}" 
	fi
}

install_packages(){
	($_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
	($_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
	$_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_}
}

check_if_package_exist_in_repo(){
	package_name="${1-}"
	if [ "$package_name" = "--no-list-of-apps-file" ];then
		shift 1
		package_name="${1-}"
		if apt list --installed ${package_name} 2>/dev/null | grep "^${package_name}/" | grep -q "[installed]";then
			return 0
		else
			return 1
		fi
	else
		if ! dpkg -s "${package_name}" > /dev/null 2>&1;then
			check_apps_in_cache="$(grep "^$package_name/" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				return 0
			fi
		fi
	fi
}

add_packages_2_install_list()
{
	localarray="$@"
	
	for INDEX in ${localarray}
	do
		if ! dpkg -s "${INDEX}" > /dev/null 2>&1;then
			check_apps_in_cache="$(grep "^$INDEX/" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_="$List_of_apt_2_install_ $INDEX"
				show_im "${INDEX} added to install apps" 
			else
				show_wm "${INDEX} does not exist." 
			fi
		fi
	done
}

upgrade_now()
{
	$_SUPERUSER ${PACKAGER} update -y
	$_SUPERUSER ${PACKAGER} -y upgrade 
}

remove_package_with_error2info()
{
	localarray="$@"
	for package in ${localarray}
	do
		if dpkg -s "${package}" >/dev/null 2>&1;then
			show_im "Purging ${package}."
			$_SUPERUSER ${PACKAGER} remove -y "$package"
		fi
	done
}

remove_unnecessary_package_manager_stuff(){
	show_im ""
}

run_package_manager_autoclean(){
	show_im ""
}

_unattended_upgrades_()
{
	auto_upgrades_file="/etc/apt/apt.conf.d/20auto-upgrades"
	if [ -f "${auto_upgrades_file}" ];then
		auto_upgrades_file_bak="/etc/apt/apt.conf.d/20auto-upgrades.bak"
		case "$1" in
			start)
				[ -f "${installer_phases}/_unattended_upgrades_start" ] && return
				
				show_im "start unattended upgrades."
				init_manager stop unattended-upgrades || :
				if [ ! -f "${auto_upgrades_file_bak}" ];then
					my-superuser mv "${auto_upgrades_file}" "${auto_upgrades_file_bak}"
				fi
				touch "${installer_phases}/_unattended_upgrades_start"
			;;
			stop)
				[ -f "${installer_phases}/_unattended_upgrades_stop" ] && return
				
				show_im "stop unattended upgrades."
				if [ -f "${auto_upgrades_file}" ] && [ -f "${auto_upgrades_file_bak}" ];then
					my-superuser rm "${auto_upgrades_file}"
				fi
					
				if [ -f "${auto_upgrades_file_bak}" ];then
					my-superuser mv "${auto_upgrades_file_bak}" "${auto_upgrades_file}"
				fi
				touch "${installer_phases}/_unattended_upgrades_stop"
			;;
		esac
	fi
}

pre_package_manager_(){
	kill_package_ ${PACKAGER}
	upgrade_now
	create_package_list
}
