#!/bin/sh
pre_disto_Drivers_installer(){
	[ -f "${installer_phases}/pre_disto_Drivers_installer" ] && return
	. "${prompt_to_install_value_file}"
	show_im "Adding needed Drivers to install list."
	install_envycontrol=false
	
	if ls /sys/class/backlight | head -n 1 | grep -q "intel_";then
		install_drivers_if_laptop="${install_drivers_if_laptop} ${install_drivers_if_laptop_xbacklight}"
	else
		install_drivers_if_laptop="${install_drivers_if_laptop} ${install_drivers_if_laptop_light}"
	fi
	
	if [ "$_cuda_" = "Y" ];then
		install_nvidia_gpu_drivers="${install_nvidia_gpu_drivers} ${install_nvidia_gpu_drivers_cuda}"
	fi
	
	if [ "$_kernel_open_dkms_" = "Y" ];then
		install_nvidia_gpu_drivers="${install_nvidia_gpu_drivers} ${install_nvidia_gpu_drivers_dkms}"
	fi
	##################################################################################
	# var
	##################################################################################
	if lsusb 2>/dev/null | grep -qi fingerprint || lspci | grep -qi fingerprint || ls /sys/bus/usb/devices/* | grep -qi fingerprint;then
    	fingerprint_exist=true
	else
		fingerprint_exist=false
	fi
	
	##################################################################################
	# function
	##################################################################################
	
	create_20_intel_conf_file(){
		show_im "Create 20-intel.conf file."
		if [ "${intel_gpu_exist}" = "true" ];then
			my-superuser mkdir -p /etc/X11/xorg.conf.d/
			my-superuser tee /etc/X11/xorg.conf.d/20-intel.conf <<- EOF > /dev/null
			Section "Device"
				Identifier  "Intel Graphics"
				Driver      "Intel"
				Option      "AccelMethod"  "sna"
				Option      "TearFree"	"True"
				Option      "Tiling"	"True"
				Option      "SwapbuffersWait" "True"
				#Option      "AccelMethod"  "uxa"
			EndSection
			EOF
		fi
	}
	
	##################################################################################
	# GPU Drivers
	##################################################################################
	if [ "${install_GPU_Drivers}" = "Y" ];then
			
		number_of_gpus=0
		lspci_output=$(lspci | grep -i 'vga')
		
		if echo "$lspci_output" | grep -iq VMware;then
			VMware_gpu_exist=true
			number_of_gpus=$((number_of_gpus + 1))
		else
			if echo "$lspci_output" | grep -iq nvidia;then
				nvidia_gpu_exist=true
				number_of_gpus=$((number_of_gpus + 1))
			fi
			
			if echo "$lspci_output" | grep -iq intel;then
				intel_gpu_exist=true
				number_of_gpus=$((number_of_gpus + 1))
			fi
			
			if echo "$lspci_output" | grep -iq amd;then
				amd_gpu_exist=true
				number_of_gpus=$((number_of_gpus + 1))
			fi
		fi
		
		[ $number_of_gpus -gt 1 ] && install_envycontrol=true
	
		if [ "$(lspci | grep "VGA compatible controller" | grep VMware -c)" != "0" ];then
			show_im "This is VM"
		fi
		
		if [ "${nvidia_gpu_exist}" = "true" ];then
			add_packages_2_install_list "${install_nvidia_gpu_drivers}"
		fi
			
		if [ "${amd_gpu_exist}" = "true" ];then
			add_packages_2_install_list "${install_amd_gpu_drivers}"
		fi
			
		if [ "${intel_gpu_exist}" = "true" ];then
			add_packages_2_install_list "${install_intel_gpu_drivers}"
		fi
		
	fi
	
	##################################################################################
	# main
	##################################################################################
	if [ "$this_is_laptop" = true ];then
		add_packages_2_install_list "${install_drivers_if_laptop}"
	fi
	
	if [ "$fingerprint_exist" = true ];then
    	add_packages_2_install_list "${install_fingerprint}"
	fi
	
	if lspci | grep -qEi 'wifi|wireless' ;then
		add_packages_2_install_list "${install_wireless}"
	fi
	
	if my-superuser dmesg | grep -qi bluetooth || my-superuser lsusb 2>/dev/null | grep -qi bluetooth || [ -d /sys/class/bluetooth ];then
		add_packages_2_install_list "${install_bluetooth}"
	fi
	
	if ! check_if_package_exist_in_repo "pipewire" ;then
		add_packages_2_install_list "${install_audio}"
	fi
	
	add_packages_2_install_list "${install_Network}"
	add_packages_2_install_list "${install_autoinstall_firmware}"
	List_of_drives_2_install_="$List_of_apt_2_install_"
	echo "List_of_drives_2_install_=\"$List_of_apt_2_install_\"" >> "${save_value_file}"
	touch "${installer_phases}/pre_disto_Drivers_installer"
}

post_disto_Drivers_installer(){
	[ -f "${installer_phases}/post_disto_Drivers_installer" ] && return
	. "${prompt_to_install_value_file}"
	show_im "Configer Drivers."
	if [ -f "/usr/sbin/isenkram-autoinstall-firmware" ];then
		show_im "run isenkram-autoinstall-firmware."
		my-superuser isenkram-autoinstall-firmware || : # to prevent script from exiting "isenkram-autoinstall-firmware contain exit command"
	fi
	show_im "Configer packages."
	
	#create_20_intel_conf_file
	
	if [ "$fingerprint_exist" = true ];then
		fingerprint_exist=true
		echo "fingerprint_exist=true" >> "${save_value_file}"
	fi
	
	if [ "$this_is_laptop" = true ];then
		show_im "some config"
	fi
	
	if [ "${install_GPU_Drivers}" = "Y" ];then
		GPU_Drivers_ready=true
		echo "GPU_Drivers_ready=true" >> "${save_value_file}"
	fi
	
	if command -v fprintd-verify > /dev/null ;then
		my-superuser pam-auth-update --enable fprintd
	fi
	
	touch "${installer_phases}/post_disto_Drivers_installer"
}
