#!/bin/sh
##################################################################################
# function
##################################################################################

check_and_download_()
{
	check_this_file_="${1-}"
	new_check_this_file_="${temp_path}/${check_this_file_}"
	check_this_file_location="$(find $HOME -type f -name ${check_this_file_} | head -1)"
	
	[ -f "${new_check_this_file_}" ] && return
	
	if [ -n "${check_this_file_location}" ];then
		mv "${check_this_file_location}" "${temp_path}"
	fi
	
	if [ ! -f "${new_check_this_file_}" ]; then
		show_im "Download $check_this_file_ file from www.github.com/dari862/my_stuff_installer ."
		if download_file "" "https://raw.githubusercontent.com/dari862/my_stuff_installer/main/core/${check_this_file_}" "${new_check_this_file_}" ;then
			chmod +x "${new_check_this_file_}"
		else
			show_em "Error: Failed to download ${check_this_file_} from ${new_check_this_file_} "
		fi
	else
		show_im "file: $check_this_file_ exsit."
	fi
}

kill_package_(){
	ps aux | grep "${1}" | awk '{print $2}' | xargs my-superuser kill -9 >/dev/null 2>&1 || :
}

if apt list --installed systemd 2>/dev/null | grep "^systemd/" | grep -q "[installed]";then
	init_system_are="systemd"
	init_manager(){
		_command="${1-}"
		_file="${2-}"
		if [ "${_command}" = "stop" ];then
			my-superuser systemctl stop ${_file}
		elif [ "${_command}" = "enable" ];then
			my-superuser systemctl enable --now ${_file}
		elif [ "${_command}" = "disable" ];then
			my-superuser systemctl disable ${_file}
		elif [ "${_command}" = "status" ];then
			my-superuser systemctl status ${_file}
		elif [ "${_command}" = "mask" ];then
			my-superuser systemctl mask ${_file}
		fi
	}
else
	show_wm "somthing went wrong. systemd not installed."
fi
######################################################################################################################
######################################################################################################################
######################################################################################################################
######################################################################################################################
######################################################################################################################

CHECK_IF_THIS_LAPTOP(){
	[ -f "${installer_phases}/CHECK_IF_THIS_LAPTOP" ] && return
	show_m "CHECK IF THIS LAPTOP"
	is_this_laptop=""
	# Are we a mac?
	if test -d /proc/pmu; then
        	batteries=$(grep Battery /proc/pmu/info | cut -f2 -d:)
        	if test "$batteries" -ne 0; then
            	is_this_laptop=true
        	fi
	fi
	
	if dmidecode="$(command -v dmidecode)" && [ -r /dev/mem -a -x "$dmidecode" ]
	then
        	# dmidecode to grab the Chassis type
        	dmitype=$("$dmidecode" --string chassis-type)
	
        	if test "$dmitype" = "Notebook" || \
           	test "$dmitype" = "Portable" || \
           	test "$dmitype" = "Laptop"   || \
           	test "$dmitype" = "Hand Held"; then
            	is_this_laptop=true
        	fi
	
        	# turn back on for debugging
        	#echo "$dmitype"
	fi
	
	if [ -e /sys/devices/virtual/dmi/id/chassis_type ] ; then
    	chassis_type="$(cat /sys/devices/virtual/dmi/id/chassis_type)"
    	case "$chassis_type" in
        	8|9|10|11) # Portable
            	is_this_laptop=true
            	;;
    	esac
	fi
	
	# check for non device ACPI batteries
	/sbin/modprobe battery 2> /dev/null || true
	sysfs_power_supply=/sys/class/power_supply
	if [ -d "$sysfs_power_supply" ]; then
		for power_supply in "$sysfs_power_supply"/*
		do
			if (
				grep -q Battery "$power_supply"/type 2>/dev/null
			) && (
				! grep -q Device "$power_supply"/scope 2>/dev/null
			)
			then
				is_this_laptop=true
			fi
		done
	fi
	# old interface:
	if [ -d /proc/acpi/battery ]; then
        	results=$(find /proc/acpi/battery -mindepth 1 -type d)
        	if [ -n "$results" ]; then
            	is_this_laptop=true
        	fi
	fi

	# check for APM batteries. This sucks, because we'll only get a valid response
	# if the laptop has a battery fitted at the time
	if [ -f /proc/apm ]; then
    	battery=$(awk '{print $6}' </proc/apm)
    	if [ "$battery" != "0xff" ] && [ "$battery" != "0x80" ]; then
        	is_this_laptop=true
    	fi
	fi
	
	if [ "${is_this_laptop}"  = true ];then
		show_im "this is laptop"
		touch "${temp_path}"/this_is_laptop
	else
		show_im "this is not laptop"
	fi
	touch "${installer_phases}/CHECK_IF_THIS_LAPTOP"
}
