#!/bin/bash
################################################################################################################################
# my_stuff.git
################################################################################################################################
cd "${my_stuff_location}"

[ -d "/usr/share/my_stuff" ] && $_SUPERUSER rm -rdf "/usr/share/my_stuff"

#run_fixes_
show_m "change ownership to root"
$_SUPERUSER chown -R root:root my_stuff

show_m "moving usr_share"
$_SUPERUSER mv my_stuff /usr/share/
$_SUPERUSER ln -sf /usr/share/my_stuff/lib/xsessions/*_openbox.desktop /usr/share/xsessions

for f in /usr/share/my_stuff/applications/* ; do
	$_SUPERUSER ln -sf "$f" /usr/share/applications
done

##################################################################################
#Theme_Stuff.git
show_m "chown of Theme_Stuff to root"
$_SUPERUSER chown -R root:root "${Theme_Stuff_location}"/Theme_Stuff

show_m "moving Theme_Stuff to /usr/share/my_stuff/Theme_Stuff"
$_SUPERUSER mv "${Theme_Stuff_location}"/Theme_Stuff /usr/share/my_stuff

show_m "Moving themes from /usr/share/themes that exist in Theme_Stuff /usr/share/my_stuff/system_files/backup"
$_SUPERUSER mkdir -p /usr/share/themes
$_SUPERUSER mkdir -p /usr/share/my_stuff/system_files/backup/themes
for d in /usr/share/my_stuff/Theme_Stuff/themes/* ; do
	Directory_name=${d##*/}
	[ -d "/usr/share/themes/${Directory_name}" ] && $_SUPERUSER mv "/usr/share/themes/${Directory_name}" /usr/share/my_stuff/system_files/backup/themes
	$_SUPERUSER ln -sf "$d" /usr/share/themes
done

show_m "Moving icons from /usr/share/icons that exist in Theme_Stuff /usr/share/my_stuff/system_files/backup"
$_SUPERUSER mkdir -p /usr/share/icons
$_SUPERUSER mkdir -p /usr/share/my_stuff/system_files/backup/icons
for d in /usr/share/my_stuff/Theme_Stuff/icons/* ; do
	Directory_name=${d##*/}
	[ -d "/usr/share/icons/${Directory_name}" ] && $_SUPERUSER mv "/usr/share/icons/${Directory_name}" /usr/share/my_stuff/system_files/backup/icons
	$_SUPERUSER ln -sf "$d" /usr/share/icons
done

show_m "Moving fonts from /usr/share/fonts that exist in Theme_Stuff /usr/share/my_stuff/system_files/backup"
$_SUPERUSER mkdir -p /usr/share/fonts
$_SUPERUSER mkdir -p /usr/share/my_stuff/system_files/backup/fonts
for e in /usr/share/my_stuff/Theme_Stuff/fonts/* ; do
	Directory_name=${e##*/}
	[ -d "/usr/share/fonts/${Directory_name}" ] && $_SUPERUSER mv "/usr/share/fonts/${Directory_name}" /usr/share/my_stuff/system_files/backup/fonts
	$_SUPERUSER ln -sf "$e" /usr/share/fonts
done

show_m "update fonts cache"
$_SUPERUSER fc-cache -vf
show_m "update icons cache"
$_SUPERUSER gtk-update-icon-cache
