#!/bin/sh
__distro_path="/usr/share/my_stuff"

pre_post_install(){
	show_im "create system ready files"
	my-superuser mkdir -p "${__distro_path}"/system_files/updater
	
	if [ -f "${temp_path}/this_is_laptop" ];then 
		show_im "this is laptop"
		my-superuser touch "${__distro_path}"/system_files/this_is_laptop
	fi
		
	if [ -f "${temp_path}/GPU_Drivers_ready" ];then 
		show_im "GPU_Drivers ready ."
		my-superuser touch "${__distro_path}"/system_files/GPU_Drivers_ready
	fi
	
	if [ -f "${temp_path}/fingerprint_exist" ];then 
		show_im "fingerprint ready ."
		my-superuser touch "${__distro_path}"/system_files/fingerprint_exist
	fi
	
	if [ -f "${temp_path}/envycontrol_updater_DmDmDmdMdMdM" ];then
		my-superuser mv "${temp_path}"/envycontrol_updater_DmDmDmdMdMdM "${__distro_path}"/system_files/updater/envycontrol
		show_im "runing envycontrol_updater"
		my-superuser ${__distro_path}/system_files/updater/envycontrol
	fi
	
	show_im "Add current distro name and icon to polybar."	
	if [ "$distro_name_" = "debian" ];then
		echo "distro_icon=" | my-superuser tee "${__distro_path}/system_files/disto_icons" >/dev/null 2>&1
		echo 'distro_name="Debian"' | my-superuser tee -a "${__distro_path}/system_files/disto_icons" >/dev/null 2>&1
	elif [ "$distro_name_" = "ubuntu" ];then
		echo "distro_icon=󰕈" | my-superuser tee "${__distro_path}/system_files/disto_icons" >/dev/null 2>&1
		echo 'distro_name="Ubuntu"' | my-superuser tee -a "${__distro_path}/system_files/disto_icons" >/dev/null 2>&1
	else
		echo "distro_icon=" | my-superuser tee "${__distro_path}/system_files/disto_icons" >/dev/null 2>&1
		echo 'distro_name="Arch Linux"' | my-superuser tee -a "${__distro_path}/system_files/disto_icons" >/dev/null 2>&1
	fi
}

create_blob_system_files(){
	my-superuser mkdir -p "${__distro_path}/system_files/blob"
	if command -v polybar >/dev/null ; then
		show_im "copy polybar blob and extra_blob to system_files/blob ."
		cd "${__distro_path}"/extra_blob/polybar
		my-superuser cp -r "${__distro_path}"/blob/polybar "${__distro_path}/system_files/blob" 
		for app in alacritty geany nitrogen;do
			if command -v $app >/dev/null ; then
				for theme in *;do
					my-superuser cp -r "${theme}/config/${app}" "${__distro_path}/system_files/blob/polybar/${theme}/config" 
				done
			fi
		done
		if command -v xfce4-panel >/dev/null ; then
			for theme in *;do
				my-superuser cp -r "${theme}/config/xfce4" "${__distro_path}/system_files/blob/polybar/${theme}/config" 
			done
		fi
		if command -v plank >/dev/null ; then
			for theme in *;do
				my-superuser cp -r "${theme}/config/plank" "${__distro_path}/system_files/blob/polybar/${theme}/config" 
				my-superuser cp -r "${theme}/cache" "${__distro_path}/system_files/blob/polybar/${theme}" 
			done
		fi
	fi
	
	
	if command -v tint2 >/dev/null ; then
		show_im "copy tint2 blob and extra_blob to system_files/blob ."
		cd "${__distro_path}"/extra_blob/tint2
		my-superuser cp -r "${__distro_path}"/blob/tint2 "${__distro_path}/system_files/blob" 
		for app in jgmenu lxterminal nitrogen;do
			if command -v $app >/dev/null ; then
				for theme in *;do
					my-superuser cp -r "${theme}/config/${app}" "${__distro_path}/system_files/blob/tint2/${theme}/config" 
				done
			fi
		done
		if command -v xfce4-panel >/dev/null ; then
			for theme in *;do
				my-superuser cp -r "${theme}/config/xfce4" "${__distro_path}/system_files/blob/tint2/${theme}/config" 
			done
		fi
	fi
}

end_of_post_install(){
	show_im "creating Package-managers library file."
	cat "${__distro_path}"/lib/Package-managers/common | my-superuser tee "${__distro_path}"/system_files/Package-manager >/dev/null 2>&1
	cat "${__distro_path}"/lib/Package-managers/${PACKAGER}.sh | my-superuser tee -a "${__distro_path}"/system_files/Package-manager >/dev/null 2>&1
	
	show_im "link icons based on distro"
	if [ -d "${__distro_path}/icons/Distro/${distro_name_}" ];then
		my-superuser ln -sf "${__distro_path}/icons/Distro/${distro_name_}" "${__distro_path}/system_files/Distro"
	else
		my-superuser ln -sf "${__distro_path}/icons/Distro/arch" "${__distro_path}/system_files/Distro"
	fi
	
	# test if in virtual machine
	if [ "$(cat /sys/devices/virtual/dmi/id/chassis_type)" = "1" ];then # 1 eq vm
		# disable vsync from picom (vsync in virtual machine make issues)
		show_im "picom vm"
		my-superuser sed -i 's|# vsync = false|vsync = false;|g' "${__distro_path}"/system_files/skel/.config/picom.conf
		my-superuser sed -i 's|# vsync = false|vsync = false;|g' "${__distro_path}"/system_files/skel/.config/picom.conf.bunsenlab
		my-superuser sed -i 's|vsync = true;|# vsync = true|g' "${__distro_path}"/system_files/skel/.config/picom.conf
		my-superuser sed -i 's|vsync = true;|# vsync = true|g' "${__distro_path}"/system_files/skel/.config/picom.conf.bunsenlab
	fi
	
	my-superuser mkdir -p "/usr/share/lightdm/lightdm.conf.d"
	my-superuser mkdir -p "/usr/share/lightdm/lightdm-gtk-greeter.conf.d"
	
	my-superuser cp -r ${__distro_path}/lib/lightdm "${__distro_path}"/system_files
	my-superuser ln -sf "${__distro_path}"/system_files/lightdm/lightdm.conf.d/50_my_stuff.conf /usr/share/lightdm/lightdm.conf.d
	my-superuser ln -sf "${__distro_path}"/system_files/lightdm/lightdm-gtk-greeter.conf.d/50_my_stuff.conf /usr/share/lightdm/lightdm-gtk-greeter.conf.d

	show_im "copy manpages."
	my-superuser ln -sf ${__distro_path}/lib/manpage/* /usr/share/man/man1
	
	show_im "installing update-notification"
	my-superuser cp -r "${__distro_path}/lib/apps/update-notification.conf" "${__distro_path}/system_files"
	. "${__distro_path}/system_files/update-notification.conf"
	my-superuser ln -sf "$script_full_path" "/etc/cron.$cron_when"	
	if [ ! -f "$updates_file" ]
	then 
		my-superuser touch "$updates_file"
		my-superuser chmod a+w "$updates_file"
	fi
	
	show_im "pick correct apps_as_root."
	my-superuser chmod -c 0400 ${__distro_path}/lib/apps/doas/doas.conf
	if command -v doas >/dev/null 2>&1;then
		my-superuser ln -sf ${__distro_path}/lib/apps/doas/apps_as_root ${__distro_path}/system_files/bin
		my-superuser ln -sf ${__distro_path}/lib/apps/doas/doasedit ${__distro_path}/system_files/bin
		my-superuser cp -r ${__distro_path}/lib/apps/doas/doas.conf /etc
		if ! my-superuser doas -C ${__distro_path}/lib/apps/doas/doas.conf;then
			show_em "config error"
		fi
	elif command -v sudo >/dev/null 2>&1;then
		my-superuser ln -sf ${__distro_path}/lib/apps/sudo/apps_as_root ${__distro_path}/system_files/bin
	fi	
	
	show_im "prepare completed"
	my-superuser touch "${installer_phases}/disto_post_install"
	
}
