#!/bin/sh
################################################################################################################################
[ -f "${installer_phases}/disto_configer" ] && return
show_im "moving Theme_Stuff to my_stuff"
$_SUPERUSER mv "${theme_temp_path}"/Theme_Stuff "${my_stuff_temp_path}"/my_stuff

show_im "change ownership to root"
$_SUPERUSER chown -R root:root "${my_stuff_temp_path}"/my_stuff

[ -d "${__distro_path}" ] && $_SUPERUSER rm -rdf "${__distro_path}"

show_im "moving usr_share"
$_SUPERUSER mv "${my_stuff_temp_path}"/my_stuff /usr/share/
$_SUPERUSER ln -sf "${__distro_path}"/lib/xsessions/*_openbox.desktop /usr/share/xsessions

for f in ${__distro_path}/applications/* ; do
	$_SUPERUSER ln -sf "$f" /usr/share/applications
done

show_im "Moving themes from /usr/share/themes that exist in Theme_Stuff ${__distro_path}/backup"
$_SUPERUSER mkdir -p /usr/share/themes
$_SUPERUSER mkdir -p "${__distro_path}"/backup/themes
for d in ${__distro_path}/Theme_Stuff/themes/* ; do
	Directory_name="$(basename "${d}")"
	[ -d "/usr/share/themes/${Directory_name}" ] && $_SUPERUSER mv "/usr/share/themes/${Directory_name}" "${__distro_path}"/backup/themes
	$_SUPERUSER ln -sf "$d" /usr/share/themes
done

show_im "Moving icons from /usr/share/icons that exist in Theme_Stuff ${__distro_path}/backup"
$_SUPERUSER mkdir -p /usr/share/icons
$_SUPERUSER mkdir -p "${__distro_path}/backup/icons"
for d in ${__distro_path}/Theme_Stuff/icons/* ; do
	Directory_name="$(basename "${d}")"
	[ -d "/usr/share/icons/${Directory_name}" ] && $_SUPERUSER mv "/usr/share/icons/${Directory_name}" "${__distro_path}/backup/icons"
	$_SUPERUSER ln -sf "$d" /usr/share/icons
done

show_im "Moving fonts from /usr/share/fonts that exist in Theme_Stuff ${__distro_path}/backup"
$_SUPERUSER mkdir -p /usr/share/fonts
$_SUPERUSER mkdir -p "${__distro_path}/backup/fonts"
for e in ${__distro_path}/Theme_Stuff/fonts/* ; do
	Directory_name="$(basename "${e}")"
	[ -d "/usr/share/fonts/${Directory_name}" ] && $_SUPERUSER mv "/usr/share/fonts/${Directory_name}" "${__distro_path}/backup/fonts"
	$_SUPERUSER ln -sf "$e" /usr/share/fonts
done

show_im "create Distro_Specific dir."
$_SUPERUSER ln -sf "${__distro_path}/All_Distro_Specific/${distro_name}" "${__distro_path}/Distro_Specific"

touch "${installer_phases}/disto_configer"
