#!/bin/bash

List_of_apt_2_install_=()
#######################
## must_install_apps_list
#######################
#must have apps
install_audio=(pulseaudio pavucontrol)
install_if_laptop=(acpi upower)
if [[ "$(ls /sys/class/backlight | head -n 1)" == *"intel_"* ]]; then
	install_if_laptop+=(xbacklight)
else
	install_if_laptop+=(light)
fi
install_fingerprint=(fprintd libpam-fprintd)
install_wireless=(wireless-tools)
install_bluetooth=(bluez blueman)
install_autoinstall_firmware=(isenkram)
