#!/bin/bash
List_of_apt_2_install_=()
package_firefox="$(check_if_package_exist_in_repo firefox)"
package_firefox_esr="$(check_if_package_exist_in_repo firefox-esr)"

##################################################################################
## must_install_apps_list
##################################################################################
#must have apps
install_must_have_apps=(jq btop xclip cbatticon xprintidle yad git lsb-release rofi picom mlocate ufw wget xwallpaper)
install_must_have_apps2=(psmisc unzip dunst xorg arandr autorandr dbus-x11 pnmixer diodon gparted inxi s-tui dfc htop hwinfo synaptic galternatives xdotool libnotify-bin gnome-keyring ntfs-3g acl xinit xdg-user-dirs lm-sensors)
install_openbox_=(openbox obconf xcape tint2)
install_image_viewer_apps=(viewnior)
install_files_manager_app=(thunar thunar-archive-plugin)
install_files_manager_support_app=(gvfs gvfs-fuse gvfs-backends file-roller baobab)
install_firefox_=($package_firefox $package_firefox_esr)
install_terminal=(kitty terminator)
install_conky_all_app=(conky-all)
install_if_laptop=(tlp tlp-rdw powertop xserver-xorg-input-synaptics xinput)
install_cli_sound_app=(mpd mpc ncmpcpp)
install_text_editer_app=(geany evince meld)
install_mediaplayer_app=(mpv)
install_x_lock_extra=(i3lock i3lock-fancy)
install_fonts=(fonts-noto fonts-droid-fallback fonts-cantarell fonts-liberation fonts-opensymbol fonts-noto-core fonts-noto-mono fonts-inconsolata)
install_themes=(papirus-icon-theme fonts-noto-color-emoji fonts-firacode fonts-font-awesome arc-theme gtk3-nocsd numix-icon-theme paper-icon-theme dmz-cursor-theme)
install_themes_tools=(xsettingsd lxappearance)
install_polkit_apps=(policykit-1 policykit-1-gnome)

# maim for ac-shots , ffmpeg for screen recoding , at for bl-beepmein , xsel for files-uploader , wmctrl for style-manager and files-uploader
install_for_scripts=(maim ffmpeg at xsel wmctrl)

#######################
## extra apps
#######################
install_xfce4_panel=(xfce4-panel xfce4-settings xfce4-clipman xfce4-whiskermenu-plugin network-manager-gnome)
install_polybar=(polybar libnm-dev)
install_qt5ct=(qt5ct qt5-style-kvantum libqt5svg5 qml-module-qtquick-controls)
install_jgmenu=(jgmenu)
install_bspwm=(bspwm sxhkd)
install_zsh=(zsh zsh-antigen zsh-autosuggestions zsh-syntax-highlighting)
#######################
## better bash
#######################
install_better_bash=(bash bash-completion)

#######################
## better shell
#######################
install_better_shell=(tar bat fzf trash-cli dos2unix command-not-found thefuck highlight lf)

#######################
## extra
#######################
install_extra_apps=(
micro 
multitail 
ncdu 
tree
nitrogen
)
