#!/bin/bash
set -e

remove_aria2=false
##################################
# only for apt
##################################
aptupdate(){
	show_im "updating your system"
	[ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ] || $_SUPERUSER apt-get update
}

aptfixer(){
		if grep -q 'deb cdrom' /etc/apt/sources.list;then
			$_SUPERUSER sed -i '/deb cdrom/d' /etc/apt/sources.list
		fi
		aptupdate
		### Fix broken packages for good measure (why not?)
		$_SUPERUSER apt-get install -yq -f 2>/dev/null || show_em "failed to $_SUPERUSER apt-get install -yq -f"
}	

install_apt_fast(){
	if ! type aria2c >/dev/null 2>&1; then
  		$_SUPERUSER apt-get install -y aria2
  		remove_aria2=true
	fi
	apt_fast_url='https://raw.githubusercontent.com/ilikenwf/apt-fast/master'
	$_SUPERUSER curl -SL --progress-bar "$apt_fast_url"/apt-fast -o /usr/local/bin/apt-fast
	$_SUPERUSER chmod +x /usr/local/bin/apt-fast
  	[ ! -f /etc/apt-fast.conf ] && $_SUPERUSER curl -SL --progress-bar "$apt_fast_url"/apt-fast.conf -o /etc/apt-fast.conf
}

enable_repo_contrib(){
(
IFS=$'\n'
	for l in $deb_lines_contrib; do
		$_SUPERUSER sed -i "s\\^$l$\\$l contrib\\" /etc/apt/sources.list
	done
)
}

enable_repo_nonfree_firmware(){
(
IFS=$'\n'
	for l in $deb_lines_nonfree_firmware; do
		$_SUPERUSER sed -i "s\\^$l$\\$l nonfreefirmware\\" /etc/apt/sources.list
	done
	$_SUPERUSER sed -i 's/nonfreefirmware/non-free-firmware/g'  /etc/apt/sources.list
)
}

enable_repo_nonfree(){
(
IFS=$'\n'
	for l in $deb_lines_nonfree; do
		$_SUPERUSER sed -i "s\\^$l$\\$l nonfreeonly\\" /etc/apt/sources.list
	done
	$_SUPERUSER sed -i 's/nonfreeonly/non-free/g'  /etc/apt/sources.list
)
}

enable_nvidia_gpu_repo(){
	if [[ ! -f "/usr/share/keyrings/nvidia-drivers.gpg" ]];then
		curl -fSsL "https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/3bf863cc.pub" | $_SUPERUSER gpg --dearmor | $_SUPERUSER tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
	fi
				
	if [[ ! -f "/etc/apt/sources.list.d/nvidia-drivers.list" ]];then 
		echo "deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/ /" | $_SUPERUSER tee /etc/apt/sources.list.d/nvidia-drivers.list > /dev/null 2>&1
	fi
}

enable_repo_(){
	local update_now=false
	if [[ "$enable_contrib" = true ]];then
		enable_repo_contrib && update_now=true
	fi
	
	if [[ "$enable_nonfree_firmware" = true ]];then
		enable_repo_nonfree_firmware && update_now=true
	fi
	
	if [[ "$enable_nonfree" = true ]];then
		enable_repo_nonfree && update_now=true
	fi
	
	if [ "${install_GPU_Drivers}" = "install_GPU" ] && [ "${nvidia_gpu_exist}" = "true" ];then
		enable_nvidia_gpu_repo
	fi

	if [ "$this_is_ubuntu" = true ];then
		$_SUPERUSER apt-get install -y software-properties-common
		$_SUPERUSER add-apt-repository -y universe
		$_SUPERUSER add-apt-repository -y multiverse
	fi
		
	if [[ "$update_now" = true ]];then
		aptupdate
	fi
}

##################################
# for rest
##################################

install_lightdm_now(){
	if [ -f "${installer_phases}/install_lightdm_now" ];then
		return
	fi
	
	install_lightdm_=(lightdm lightdm-gtk-greeter-settings)
	show_im "installing ( lightdm )."
	
	if [ -f "/etc/X11/default-display-manager" ]; then
		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
		[ "$d_d_m" != "lightdm"  ] && lightdm_does_not_exist=true
	else
		lightdm_does_not_exist=true
	fi
	
	if [ "$lightdm_does_not_exist" = true  ];then
		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_[@]} && kill_package_ apt-get) || \
		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_[@]} && kill_package_ apt-get) || \
		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_[@]} || (show_em "failed to install lightdm")
		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1 || (show_em "failed to change default-display-manager")
		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm || (show_em "failed to dpkg-reconfigure lightdm")
	else
		show_im "lightdm already exist."
	fi
	touch "${installer_phases}/install_lightdm_now"
}

create_package_list(){
	# create list_of_apps file
	if [[ ! -f "${list_of_apps_file_path}" ]];then
		show_im "create_list_of_apps"
		apt list 2>/dev/null > "${list_of_apps_file_path}" 
	fi
}

install_packages(){
	($_SUPERUSER ${PACKAGER} install -yq "${List_of_apt_2_install_[@]}" && kill_package_ ${PACKAGER}) || \
	($_SUPERUSER ${PACKAGER} install -yq "${List_of_apt_2_install_[@]}" && kill_package_ ${PACKAGER}) || \
	$_SUPERUSER ${PACKAGER} install -yq "${List_of_apt_2_install_[@]}"
}

check_if_package_exist_in_repo(){
	local package_name="${1-}"
	if ! dpkg -s "${package_name}" > /dev/null 2>&1; then
		check_apps_in_cache="$(grep "^$package_name/" "${list_of_apps_file_path}" 2>/dev/null || :)"
		if [ -n "${check_apps_in_cache}" ];then
			echo "${package_name}" 
		fi
	fi
}

add_packages_2_install_list()
{
	localarray=("$@")
	
	for INDEX in "${localarray[@]}"
	do
		if ! dpkg -s "${INDEX}" > /dev/null 2>&1; then
			check_apps_in_cache="$(grep "^$INDEX/" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_+=("$INDEX") 
				show_im "${INDEX} added to install apps" 
			else
				show_wm "${INDEX} does not exist." 
			fi
		fi
	done
}

upgrade_now()
{
	$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -y upgrade
	$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -y dist-upgrade
	$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -y full-upgrade
}

remove_package_with_error2info()
{
	localarray=("$@")
	for package in "${localarray[@]}"
	do
		if dpkg -s "${package}" &>/dev/null; then
			show_im "Purging ${package}."
			$_SUPERUSER apt-get purge -y "$package"
		fi
	done
}

remove_unnecessary_package_manager_stuff(){
	show_im "removing apt-fast and conf"
	[ "$remove_aria2" = true ] && show_im "removing aria2 package" && $_SUPERUSER apt-get purge -y aria2
	[ -f /usr/local/bin/apt-fast ] && show_im "removing apt-fast" && $_SUPERUSER rm -f /usr/local/bin/apt-fast
	[ -f /etc/apt-fast.conf ] && show_im "removing apt-fast.conf" && $_SUPERUSER rm -f /etc/apt-fast.conf
}

run_package_manager_autoclean(){
	show_im "autoremove unwanted pakages"
	$_SUPERUSER apt-get autoremove -y
	$_SUPERUSER apt-get autoclean -y
}

_unattended_upgrades_()
{
	auto_upgrades_file="/etc/apt/apt.conf.d/20auto-upgrades"
	if [ -f "${auto_upgrades_file}" ];then
		auto_upgrades_file_bak="/etc/apt/apt.conf.d/20auto-upgrades.bak"
		case "$1" in
			start)
				if [ -f "${installer_phases}/_unattended_upgrades_start" ];then
					return
				fi
				show_im "start unattended upgrades."
				init_manager stop unattended-upgrades || :
				if [ ! -f "${auto_upgrades_file_bak}" ];then
					my-superuser mv "${auto_upgrades_file}" "${auto_upgrades_file_bak}"
				fi
				touch "${installer_phases}/_unattended_upgrades_start"
			;;
			stop)
				if [ -f "${installer_phases}/_unattended_upgrades_stop" ];then
					return
				fi
				show_im "stop unattended upgrades."
				if [ -f "${auto_upgrades_file}" ] && [ -f "${auto_upgrades_file_bak}" ];then
					my-superuser rm "${auto_upgrades_file}"
				fi
					
				if [ -f "${auto_upgrades_file_bak}" ];then
					my-superuser mv "${auto_upgrades_file_bak}" "${auto_upgrades_file}"
				fi
				touch "${installer_phases}/_unattended_upgrades_stop"
			;;
		esac
	fi
}

pre_package_manager_(){
	init_manager stop apt-daily.timer
	init_manager stop apt-daily-upgrade.timer
	aptfixer
	enable_repo_
	install_apt_fast || :
	
	if command -v apt-get &>/dev/null;then
		PACKAGER="apt-get"
	elif command -v apt-fast &>/dev/null;then
		PACKAGER="apt-fast"
	fi
	upgrade_now
	create_package_list
}
