#!/bin/sh
##################################################################################
# function
##################################################################################

check_and_download_()
{
	check_this_file_="${1:-}"
	file_dir="${2:-}"
	show_im "running check_and_download_ function on \"$check_this_file_\" \"$file_dir\""
	new_check_this_file_="${temp_path}/${check_this_file_}"
	if [ -d "$HOME/Desktop" ];then
		dir_2_find_files_in="$HOME/Desktop ${temp_path}"
	else
		dir_2_find_files_in="${temp_path}"
	fi
	if [ -z "${file_dir}" ];then
		url_to_download="${check_this_file_}"
		check_this_file_location="$(find ${dir_2_find_files_in} -type f -name ${check_this_file_} || :)"
	else
		url_to_download="${file_dir}/${check_this_file_}"
		check_this_file_location="$(find ${dir_2_find_files_in} -type f -name ${check_this_file_} | grep "${file_dir}" || :)"
	fi
		
	[ -f "${new_check_this_file_}" ] && return
	
	if [ -n "${check_this_file_location}" ] && [ "${check_this_file_location}" != "${temp_path}/${check_this_file_}" ];then
		mv "${check_this_file_location}" "${temp_path}"
	fi
	
	if [ ! -f "${new_check_this_file_}" ];then
		show_im "Download $check_this_file_ file from www.github.com/dari862/my_stuff_installer ."
		if download_file "" "https://raw.githubusercontent.com/dari862/my_stuff_installer/main/core/${url_to_download}" "${new_check_this_file_}" ;then
			chmod +x "${new_check_this_file_}"
		else
			show_em "Error: Failed to download ${check_this_file_} from https://raw.githubusercontent.com/dari862/my_stuff_installer/main/core/${check_this_file_}"
		fi
	else
		show_im "file: $check_this_file_ exsit."
	fi
}

kill_package_(){
	my-superuser ps aux | grep "${1}" | awk '{print $2}' | xargs my-superuser kill -9 >/dev/null 2>&1 || :
}

######################################################################################################################
######################################################################################################################
######################################################################################################################
######################################################################################################################
######################################################################################################################

CHECK_IF_THIS_LAPTOP(){
	[ -f "${installer_phases}/CHECK_IF_THIS_LAPTOP" ] && return
	show_m "CHECK IF THIS LAPTOP"
	is_this_laptop=""
	# Are we a mac?
	if test -d /proc/pmu;then
        	batteries=$(grep Battery /proc/pmu/info | cut -f2 -d:)
        	if test "$batteries" -ne 0;then
            	is_this_laptop=true
        	fi
	fi
	
	if dmidecode="$(command -v dmidecode)" && [ -r /dev/mem -a -x "$dmidecode" ]
	then
        	# dmidecode to grab the Chassis type
        	dmitype=$("$dmidecode" --string chassis-type)
	
        	if test "$dmitype" = "Notebook" || \
           	test "$dmitype" = "Portable" || \
           	test "$dmitype" = "Laptop"   || \
           	test "$dmitype" = "Hand Held";then
            	is_this_laptop=true
        	fi
	
        	# turn back on for debugging
        	#echo "$dmitype"
	fi
	
	if [ -e /sys/devices/virtual/dmi/id/chassis_type ];then
    	chassis_type="$(cat /sys/devices/virtual/dmi/id/chassis_type)"
    	case "$chassis_type" in
        	8|9|10|11) # Portable
            	is_this_laptop=true
            	;;
    	esac
	fi
	
	# check for non device ACPI batteries
	/sbin/modprobe battery 2> /dev/null || true
	sysfs_power_supply=/sys/class/power_supply
	if [ -d "$sysfs_power_supply" ];then
		for power_supply in "$sysfs_power_supply"/*
		do
			if (
				grep -q Battery "$power_supply"/type 2>/dev/null
			) && (
				! grep -q Device "$power_supply"/scope 2>/dev/null
			)
			then
				is_this_laptop=true
			fi
		done
	fi
	# old interface:
	if [ -d /proc/acpi/battery ];then
        	results=$(find /proc/acpi/battery -mindepth 1 -type d)
        	if [ -n "$results" ];then
            	is_this_laptop=true
        	fi
	fi

	# check for APM batteries. This sucks, because we'll only get a valid response
	# if the laptop has a battery fitted at the time
	if [ -f /proc/apm ];then
    	battery=$(awk '{print $6}' </proc/apm)
    	if [ "$battery" != "0xff" ] && [ "$battery" != "0x80" ];then
        	is_this_laptop=true
    	fi
	fi
	
	if [ "${is_this_laptop}" = true ];then
		show_im "this is laptop"
		this_is_laptop=true
		echo "this_is_laptop=true" >> "${save_value_file}"
	else
		show_im "this is not laptop"
	fi
	touch "${installer_phases}/CHECK_IF_THIS_LAPTOP"
}
