#!/bin/bash
set -e
##################################################################################
# var
##################################################################################
install_GPU_now="${1-}"
List_of_apt_2_install_=()
fingerprint_exist=false

#######################
## must_install_apps_list
#######################
#must have apps
install_audio=(pulseaudio pavucontrol)
install_if_laptop=(acpi upower)
if [[ "$(ls /sys/class/backlight | head -n 1)" == *"intel_"* ]]; then
	install_if_laptop+=(xbacklight)
else
	install_if_laptop+=(light)
fi
install_fingerprint=(fprintd libpam-fprintd)
install_wireless=(wireless-tools)
install_bluetooth=(bluez blueman)
install_autoinstall_firmware=(isenkram)

if lsusb | grep -i fingerprint >/dev/null || lspci | grep -i fingerprint >/dev/null || ls /sys/bus/usb/devices/* | grep -i fingerprint >/dev/null; then
    fingerprint_exist=true
fi

##################################################################################
# function
##################################################################################

create_20_intel_conf_file(){
	show_m "Create 20-intel.conf file."
	if [ "${intel_gpu_exist}" = "true" ];then
	sudo mkdir -p /etc/X11/xorg.conf.d/
sudo bash -c 'cat << EOF > /etc/X11/xorg.conf.d/20-intel.conf
Section "Device"
	Identifier  "Intel Graphics"
	Driver      "Intel"
	Option      "AccelMethod"  "sna"
	Option      "TearFree"	"True"
	Option      "Tiling"	"True"
	Option      "SwapbuffersWait" "True"
	#Option      "AccelMethod"  "uxa"
EndSection
EOF'
	fi
}

##################################################################################
# GPU Drivers
##################################################################################
if [[ "${install_GPU_now}" = "install_GPU" ]];then
	if [ "$(lspci | grep "VGA compatible controller" | grep VMware -c)" != "0" ];then
		echo "This is VM"
	else
		if [ "${nvidia_gpu_exist}" = "true" ];then
			_cuda_="${2-}"
			_kernel_open_dkms_="${3-}"
			add_packages_2_install_list "nvidia-driver nvidia-smi nvidia-settings $_kernel_open_dkms_ $_cuda_"
		fi
		
		if [ "${amd_gpu_exist}" = "true" ];then
			add_packages_2_install_list "libgl1-mesa-dri xserver-xorg-video-ati xserver-xorg-video-amdgpu mesa-vulkan-drivers vkbasalt"
		fi
		
		if [ "${intel_gpu_exist}" = "true" ];then
			add_packages_2_install_list "xserver-xorg-video-intel intel-gpu-tools intel-media-va-driver"
		fi
	fi
fi

##################################################################################
# main
##################################################################################

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	add_packages_2_install_list "${install_if_laptop[@]}"
fi

if [[ "$fingerprint_exist" = true ]];then
    add_packages_2_install_list "${install_fingerprint[@]}"
fi

if lspci | egrep -i 'wifi|wireless' 1>/dev/null ;then
	add_packages_2_install_list "${install_wireless[@]}"
fi

if sudo dmesg | grep -i bluetooth 1>/dev/null || sudo lsusb | grep -i bluetooth 1>/dev/null ;then
	add_packages_2_install_list "${install_bluetooth[@]}"
fi

add_packages_2_install_list "${install_audio[@]}"
add_packages_2_install_list "${install_Network[@]}"
add_packages_2_install_list "${install_autoinstall_firmware[@]}"

if [[ "${install_GPU_now}" = "install_GPU" ]];then
	if [[ $PACKAGER == "apt-get" ]]; then
		if [ "${nvidia_gpu_exist}" = "true" ];then
			if [[ ! -f "/usr/share/keyrings/nvidia-drivers.gpg" ]];then
				curl -fSsL "https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/3bf863cc.pub" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
			fi
			
			if [[ ! -f "/etc/apt/sources.list.d/nvidia-drivers.list" ]];then 
				echo "deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/ /" | sudo tee /etc/apt/sources.list.d/nvidia-drivers.list
			fi
		fi
	fi
fi

if [[ $PACKAGER == "apt-get" ]]; then		
	if [ "$this_is_ubuntu" = true ];then
		sudo apt-get install -y software-properties-common
		sudo add-apt-repository -y universe
		sudo add-apt-repository -y multiverse
	fi
	show_m "Running Update."
	aptupdate	
fi
install_packages

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	show_m "this is laptop"
	if [ "$number_of_gpus" -gt 1 ]; then
		show_m "create envycontrol installtion file."
cat << 'EOF' > "${temp_path}"/envycontrol_updater_DmDmDmdMdMdM
	envycontrol_updater_path="$(mktemp -d)" 
	distroname="DmDmDmdMdMdM"
	wget -qO- 'https://api.github.com/repos/bayasdev/envycontrol/releases/latest' \
  	| grep '"tarball_url"' \
  	| cut -f2,3 -d':' \
  	| tr -d '"' \
  	| tr -d ',' \
  	| xargs wget -O "${envycontrol_updater_path}"/envycontrol.tar.gz && tar -xvzf "${envycontrol_updater_path}"/envycontrol.tar.gz -C "${envycontrol_updater_path}" && mv "${envycontrol_updater_path}"/bayasdev* "${envycontrol_updater_path}"/envycontrol
  	
  	[ -d "/usr/share/${distroname}/opt/downloaded/envycontrol" ] && sudo rm -rdf "/usr/share/${distroname}/opt/downloaded/envycontrol"
  	[ ! -d "/usr/share/${distroname}/opt/downloaded" ] && sudo mkdir -p /usr/share/${distroname}/opt/downloaded
  	[ ! -d "/usr/share/${distroname}/opt/git" ] && sudo mkdir -p /usr/share/${distroname}/opt/git
  	
  	if [ -d "${envycontrol_updater_path}"/envycontrol ];then
  		chmod +x "${envycontrol_updater_path}"/envycontrol/envycontrol.py 
  		sudo mv "${envycontrol_updater_path}"/envycontrol "/usr/share/${distroname}/opt/git/"
  		ln -sf "/usr/share/${distroname}/opt/downloaded/envycontrol/envycontrol.py" "/usr/share/${distroname}/bin/bin/envycontrol"
  	fi
EOF
		chmod +x "${temp_path}"/envycontrol_updater_DmDmDmdMdMdM
	fi
fi
show_m "run isenkram-autoinstall-firmware."
sudo isenkram-autoinstall-firmware || : # to prevent script from exiting "isenkram-autoinstall-firmware contain exit command"

show_m "Remove isenkram package."
apt_purge_with_error2info "${install_autoinstall_firmware[@]}"

show_m "Configer packages."

#create_20_intel_conf_file

if [[ "$fingerprint_exist" = true ]];then
	mktemp "${temp_path}"/fingerprint_exist_XXXXXX
fi

if [[ "$(CHECK_IF_THIS_LAPTOP)"  = true ]];then
	show_m "some config"
fi

if [[ "${install_GPU_now}" = "install_GPU" ]];then
	mktemp "${temp_path}"/GPU_Drivers_ready_XXXXXX
fi

if command -v fprintd-verify > /dev/null ;then
	sudo pam-auth-update --enable fprintd
fi
