#!/bin/sh
#must have apps
install_audio=""
install_drivers_if_laptop=""
install_drivers_if_laptop_xbacklight="xbacklight"
install_drivers_if_laptop_light=""
install_wireless="wireless-tools"
install_bluetooth="bluez blueman"
install_autoinstall_firmware="fwupd"
install_exfat=""
