greeter_background="/usr/share/my_stuff/my_wallpapers/owl4ce_wall-01.jpg"
greeter_theme_name="Fleon"
greeter_icon_theme_name="Papirus-Dark-Custom"
greeter_font_name="Cantarell 9"
greeter_position="57%,start 22%,start"
