#!/bin/sh
#
# https://www.youtube.com/watch?v=6pUDzv49M68
sudo pacman -Sy
sudo pacman -Sy base linux linux-firmware base-devel xf86-video-fbdev xorg xorg-xinit git feh picom firefox polybar python-pywal ttf-jetbrains-mono thunar
mkdir -p /tmp/suckless
cd /tmp/suckless
for repo in dwm dmenu st;do
	git clone https://github.com/umrian/$repo
	cd $repo
	sudo make clean install
	cd ..
done
git clone https://github.com/umrian/dotfiles
cd dotfiles

mv .xinitrc start_dwm
sudo chown root:root start_dwm
sudo chmod +x start_dwm
sudo mv start_dwm /usr/bin
mv wallpapers ~/
feh --bg-fill wallpapers/pepper-carrot.jpg > /dev/null 2>&1
mkdir -p ~/.config/polybar
mkdir -p ~/.config/picom
mv config.ini ~/.config/polybar
mv picom.conf ~/.config/picom
tee /usr/share/xsessions/my_stuff_dwm.desktop << EOF > /dev/null 2>&1
[Desktop Entry]
Name=My Stuff dwm
Comment=Log in to a My Stuff dwm session
Exec=/usr/bin/start_dwm
TryExec=/usr/bin/start_dwm
Icon=openbox
Type=Xsession
EOF
sudo reboot
