#!/bin/sh
#x11-utils
#xserver-xorg-input-all
#x11-xserver-utils
#xserver-xorg-input-synaptics
#dbus-x11

_X11_packages="diodon polybar libnm-dev bspwm sxhkd jgmenu xinput xinit xclip xwallpaper xdotool xprintidle yad cbatticon rofi picom dunst nsxiv arandr autorandr i3lock conky openbox obconf xcape tint2 xsettingsd lxappearance slop wmctrl"

cd "$HOME/Desktop/my_stuff/"

for package in ${_X11_packages};do
	echo "#-------------------------------------#"
	echo "#- ${package} -#"
	echo "#-------------------------------------#"
	grep -rI "${package}"
done | grep -vE "^All_Distro_Specific/|^lib/|^applications_extra/|^blob/|^bin/my_installer|^distro_manager|^bin/X11|^blob_extra/|^skel_extra|^bin/shell-guide" > "$HOME/Desktop/X11_output"
