#!/bin/sh
need_reboot=false
need_update=false
if ! grep -q " trixie " /etc/apt/sources.list;then
	sudo sed -i "s/bookworm/trixie/g" /etc/apt/sources.list
	need_update=true
	need_reboot=true
fi

sudo sed -i "s/^# deb-src/#deb-src/g" /etc/apt/sources.list

if grep -q "^#deb-src" /etc/apt/sources.list;then
	sudo sed -i "s/^#deb-src/deb-src/g" /etc/apt/sources.list
	need_update=true
fi

if [ "$need_update" = true ];then
	if sudo apt-get update;then
		sudo apt-get install apt
		sudo apt-get install debian-keyring
		sudo apt-get -y upgrade
		sudo apt-get -y full-upgrade
		sudo apt-get -y autoremove
		if [ "$need_reboot" = true ];then
			sudo reboot
		fi
	else
		exit 1
	fi
fi
git clone --depth=1 https://github.com/JaKooLit/Debian-Hyprland.git ~/Debian-Hyprland
cd ~/Debian-Hyprland
chmod +x install.sh
./install.sh
