#!/bin/sh
must_purge="system-config-printer zeitgeist"

#######################
## must have apps
#######################
install_ufw_apps="ufw"
install_must_have_apps="jq git plocate htop unzip libnotify"
install_must_have_apps2="psmisc gparted inxi s-tui dfc hwinfo pamac-aur xdotool acl lm_sensors ntfs-3g"
install_image_viewer_apps="viewnior imagemagick gtk-engine-murrine"
install_files_manager_support_app="gvfs gvfs-mtp gvfs-afc file-roller baobab avahi"
install_terminal="kitty xdg-desktop-portal xdg-desktop-portal-gtk"
install_if_laptop_apps="tlp tlp-rdw powertop"
install_cli_sound_app="mpd mpc ncmpcpp"
install_MIDI_sound_app="wildmidi timidity++"
install_text_editer_app="geany geany-plugins zathura"
install_mediaplayer_app="mpv cava"
install_polkit_apps="polkit polkit-gnome gnome-keyring"
install_fonts="noto-fonts ttf-droid cantarell-fonts ttf-liberation ttf-opensans ttf-inconsolata"
install_passman="keepassxc"

#firefox
install_firefox_="firefox"

# ffmpeg for screen recoding and manymore , at for bl-beepmein , bind (dig) for get_public_ip
install_for_scripts="ffmpeg at bind"

#for x11
install_X11_apps="xorg-xprop xorg-server xorg-xinput dbus xorg-xinit xdg-user-dirs xorg-xdpyinfo xclip xwallpaper xdotool xprintidle"
install_must_have_apps_for_X11="yad rofi picom dunst nsxiv "
install_res_apps_for_X11="arandr"
install_locker_app_for_X11="i3lock"
install_if_laptop_apps_x11="xf86-input-synaptics"
install_conky_all_app="conky"
install_openbox_="openbox obconf-qt-git xcape tint2 xorg-xset"
install_themes_tools_for_X11="xsettingsd lxappearance"
# slop for ac-shots and screen recoding , wmctrl for style-manager and files-uploader
install_for_x11_scripts="slop wmctrl"

#for wayland


#######################
## extra apps
#######################
install_files_manager_thunar="thunar thunar-archive-plugin tumbler"
install_files_manager_pcmanfm="pcmanfm"
install_qt5ct="qt5ct kvantum qt5-svg qt5-quickcontrols"
install_zsh="zsh"

#for x11
#install_clipman_manager_for_X11="parcellite"
#install_clipman_manager_for_X11="clipmenu"
#install_clipman_manager_for_X11="diodon"
#install_clipman_manager_for_X11="xfce4-clipman"
install_polybar="polybar libnm-dev"
install_apps_for_bspwm="bspwm sxhkd"
install_apps_for_dwm="base-devel"
install_jgmenu="jgmenu"

#for wayland


#######################
## better bash
#######################
install_better_bash="bash bash-completion"

#######################
## better shell
#######################
install_better_shell="tar bat fzf pkgfile thefuck highlight lf"

#######################
## extra
#######################
install_extra_apps="micro multitail ncdu tree meld btop"
