#!/bin/sh
#must have apps
install_audio="pulseaudio pavucontrol"
install_drivers_if_laptop="acpi upower"
install_drivers_if_laptop_xbacklight="xorg-xbacklight"
install_drivers_if_laptop_light="light"
install_fingerprint="fprintd libfprint"
install_wireless="wireless_tools"
install_bluetooth="bluez bluez-utils blueman"
install_autoinstall_firmware="" # No direct equivalent in Arch, use 'linux-firmware' if needed
install_nvidia_gpu_drivers="nvidia nvidia-utils nvidia-settings"
install_amd_gpu_drivers="mesa xf86-video-ati xf86-video-amdgpu vulkan-radeon vkbasalt"
install_intel_gpu_drivers="xf86-video-intel intel-gpu-tools intel-media-driver"
install_nvidia_gpu_drivers_cuda="cuda"
install_nvidia_gpu_drivers_dkms="nvidia-dkms"
