#!/bin/sh
sh_scripts="$(grep -rm1 "#\!/" -I ~/Desktop/my_stuff | grep -v "/.git/" | awk -F: '{print $1}')"
script_2_fix=""
for script in ${sh_scripts};do
	if shellcheck -i SC2086 $script | grep -q "\[";then
		script_2_fix="$script\n$script_2_fix"
	fi
done
if [ -n "$script_2_fix" ];then
	printf "$script_2_fix" > ~/Desktop/script_2_fix
fi
