#!/bin/sh
set -e

#YadAppsStore
repos="
my_stuff
Theme_Stuff
my_stuff_installer
secureMyLinux
"

# Color output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No color

push_now() {
    repo_name="$1"
    printf "\n-------------------------------------------------------\n"
	printf "  Pulling repository: %s" "$repo"
	printf "\n-------------------------------------------------------\n"
    echo "🔍 Checking repo: $repo_name"
    git pull
    printf "\n\n"
}

repos_name=$(printf "%s" "$repos" | tr '\n' ' ')
printf "#######################################################"
printf "\n#######################################################\n"
printf "Starting push for all Git repositories: %s" "$repos_name"
printf "\n#######################################################"
printf "\n#######################################################\n"

for repo in ${repos}; do
    repo_path="$HOME/Desktop/$repo"
    if [ -d "$repo_path" ]; then
        cd "$repo_path" || { echo "Failed to cd into $repo_path"; continue; }
        push_now "$repo"
    else
        echo "Directory not found: $repo_path"
    fi
done
