#!/bin/bash
unalias -a
. "/usr/share/my_stuff/lib/common/WM"
run_rofi_test(){
	panel="${1:-}"
	cd $HOME/.config/blob/$panel
	panel_changer $panel
	sleep 2
    for t in *;do
        [ -f "$t" ] && continue
        style_changer "$panel" $t >/dev/null 2>&1
        sleep 2
        echo "style name are : $t"
        echo "style name are : $t"
        echo "style name are : $t"
        . "${Distro_config_file}"
        rofi -dmenu -theme "$HOME/.config/rofi/$ROFI_STYLE/askpass.rasi"
        rofi-launcher
        rofi-music
        my_session_manager_menu
        rofi-runner
        rofi-bluetooth
        rofi-screenshot
        rofi-windows
        RiceSelector
        WallSelect
    done
}

need_testing_wrong_colors(){
	cd $HOME/.config/blob/polybar
    for t in Tokyo_City Neon_punk EVA Kernel JS_Coffee Japanese_Street BlackArch Chad_WM Japanese_City Neon ICE_Moon The_Warriors Black_And_Red HTB hack Hacker_Den Red_Mountains;do
        style_changer polybar $t >/dev/null 2>&1
        sleep 2
        echo "style name are : $t"
        echo "style name are : $t"
        echo "style name are : $t"
        . "${Distro_config_file}"
        rofi -dmenu -theme "$HOME/.config/rofi/$ROFI_STYLE/askpass.rasi"
        rofi-launcher
        rofi-music
    done
}

#run_rofi_test polybar
#run_rofi_test tint2
need_testing_wrong_colors
