#!/usr/bin/env bash

# https://github.com/onespaceman/menu-calc
# Calculator for use with rofi/dmenu(2)
# Copying to the clipboard requires xclip

copy_to_clipboard() {
  if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    echo "$1" | wl-copy
  else
    echo "$1" | xclip -selection clip
  fi
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ];then
  echo "$(tput bold)menu-calc$(tput sgr0)"
  echo "A calculator for Rofi/dmenu(2)"
  echo
  echo "$(tput bold)Usage:$(tput sgr0)"
  echo "    = 4+2"
  echo "    = (4+2)/(4+3)"
  echo "    = 4^2"
  echo "    = sqrt(4)"
  echo "    = c(2)"
  echo
  echo "$(tput bold)Passing arguments to Rofi/dmenu(2):$(tput sgr0)"
  echo
  echo "    = <Rofi args>"
  echo
  echo "The answer can be copied to the clipboard and used for further calculations inside (or outside) Rofi/dmenu."
  echo
  exit
fi

# Grab the answer
menu="$(command -v rofi) -dmenu -lines 3"
eq="$($menu -p =)"
if [ -n "$eq" ];then
	answer=$(calc $eq | sed '/\./ s/\.\{0,1\}0\{1,\}$//')
	
	action=$(echo -e "Copy to clipboard\nClear\nClose" | $menu "$@" -p "= $answer")
fi
case $action in
  "Clear") $0 ;;
  "Copy to clipboard") copy_to_clipboard "$answer" ;;
  "Close") ;;
  "") ;;
  *) $0 ;;
esac
