#!/bin/sh
set -eu

picked_cfg="${1-}"
MENU="rofi -dmenu -p"
database="./confedit-list"

if [ -z "$picked_cfg" ];then
	cfg=$(sed -e '/^[[:space:]]*$/d' -e '/^*/d' $database | column -s '##' -t | ${MENU} 'Choose File to edit:' | grep -oP "\|.*" | sed 's/| //') || exit 1
else
	cfg=$(grep "$picked_cfg" $database | grep -oP "\|.*" | sed 's/| //')
fi

if [ -n "$cfg" ];then
	if [ -z "$picked_cfg" ];then
		popup_terminal --editor "$cfg"
	else
		$CLI_EDITER "$cfg"
	fi
fi
