#!/bin/sh
set -eu

MENU="rofi -dmenu -p"

help() {
    printf '%s' "Usage: $(basename "$0") [options]
Description: Mount/unmount usb drives using dmenu. No fancy daemon required.
Dependencies: rofi, udisks2

The folowing OPTIONS are accepted:
    -h  displays this help page
    -m  mount using 'rofi'
    -u  umount using 'rofi'

Running" " $(basename "$0") " "without any argument displays this help text."
}

drive_count() {
    count="$(echo "$1" | wc -l)"
}

mount_all() {
    printf '%s\n' "$mountable" | while IFS= read -r drive; do
        udisksctl mount -b "${drive%% *}"
    done
}

unmount_all() {
    printf '%s\n' "${mounted%%* }" | while IFS= read -r drive; do
        udisksctl unmount -b "$drive"
        # done < <(printf '%s\n' "$mounted")
    done
}

mount() {
    mountable="$(lsblk -lp | awk '/^\/dev\/sd.*part $/ { print $1 " ("$4")" }')"
    [ "$mountable" = "" ] && exit 1

    drive_count "$mountable"
    [ "$count" = "1" ] && options="$mountable" || options="$mountable\nall"

    chosen="$(printf '%s' "$options" | ${MENU} "Drive to mount?")" || exit 1
    if [ "$chosen" = "all" ]; then
        mount_all
    else
        udisksctl mount -b "${chosen%% *}"
    fi
}

unmount() {
    # mounted="$(lsblk -lp | awk '/run/ { print $1 }')"
    mounted="$(lsblk -lp | grep 'run')"
    [ "$mounted" = "" ] && exit 1

    # drive_count "$mounted"
    drive_count "${mounted%%* }"
    # [ "$count" = "1" ] && options="$mounted" || options="$mounted\nall"
    [ "$count" = "1" ] && options="${mounted%%* }" || options="${mounted%%* }\nall"

    chosen="$(printf '%s' "${options}" | ${MENU} "Drive to unmount?")"
    if [ "$chosen" = "all" ]; then
        unmount_all
    else
        udisksctl unmount -b "$chosen"
    fi
}

no_opt=1
while getopts "umh" arg 2>/dev/null; do
    case "${arg}" in
    u) mount
        ;;
    m) unmount
        ;;
    h) help ;;
    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
    esac
    no_opt=0
done

# If script is run with NO argument, it will use 'dmenu'
[ $no_opt = 1 ] && help "$@"
