#!/bin/sh
#
# Script name: dm-websearch
# Description: Search various search engines (inspired by surfraw).
# Dependencies: dmenu, fzf, rofi, brave (change DMMBROWSER in dmscripts config if using another browser)
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Ali Furkan Yıldız
#               HostGrady
#               Simon Ingelsson

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.

set -eu

picked_engine="${1-}"
picked_query="${2-}"
DMBROWSER="firefox"
MENU="rofi -dmenu -p"
database="./search-engine-list"

if [ -z "$picked_engine" ];then
	engine=$(sed -e '/^[[:space:]]*$/d' -e '/^*/d' $database | column -s '#' -t | ${MENU} 'Choose search engine:' | grep -oP "https://.*") || exit 1
else
	engine=$(grep "$picked_engine" $database | grep -oP "https://.*")
fi

if [ -z "$picked_engine" ];then
	# Searching the chosen engine.
	query=$(${MENU} "$engine:")
else
	query="$picked_engine"
fi

if [ -n "$query" ];then
	query="$(printf "${query}" | jq -s -R -r @uri)"
	
	${DMBROWSER} "${engine}${query}"
fi
