#!/bin/sh
set -e

remove_aria2=false

##################################
# only for apt
##################################
aptupdate(){
	show_sm "updating your system"
	[ "$(find /var/cache/apt/pkgcache.bin -mtime 0 2>/dev/null)" ] || $_SUPERUSER apt-get update
}

aptfixer(){
	show_sm "running aptfixer"
	if grep -q 'deb cdrom' /etc/apt/sources.list;then
		$_SUPERUSER sed -i '/deb cdrom/d' /etc/apt/sources.list
	fi
	aptupdate
	$_SUPERUSER apt-get install -yq -f 2>/dev/null || show_em "failed to $_SUPERUSER apt-get install -yq -f"
}	

install_apt_fast(){
	if ! type aria2c >/dev/null 2>&1;then
		show_sm "add aria2c to purge list"
  		$_SUPERUSER apt-get install -y aria2
  		remove_aria2=true
	fi
	
	show_sm "download apt-fast"
	apt_fast_url='https://raw.githubusercontent.com/ilikenwf/apt-fast/master'
	download_file "$_SUPERUSER" "${apt_fast_url}/apt-fast" "/usr/local/bin/apt-fast"
	
	show_sm "install apt-fast"
	$_SUPERUSER chmod +x /usr/local/bin/apt-fast
  	[ ! -f /etc/apt-fast.conf ] && download_file "$_SUPERUSER" "${apt_fast_url}/apt-fast.conf" "/etc/apt-fast.conf"
}

enable_repo_contrib(){
	show_sm "enable_repo_contrib"
	while IFS= read -r line;do
		if echo "${line}" | grep -E "^(deb|deb-src) (${mirror}|${mirror_security})" | grep -qv contrib;then
			$_SUPERUSER sed -i "s|^${line}$|${line} contrib|g" /etc/apt/sources.list
		fi
	done < /etc/apt/sources.list
}

enable_repo_nonfree_firmware(){
	show_sm "enable_repo_nonfree_firmware"
	while IFS= read -r line;do
		if echo "${line}" | grep -E "^(deb|deb-src) (${mirror}|${mirror_security})" | grep -qv 'non-free-firmware';then
			$_SUPERUSER sed -i "s|^${line}$|${line} nonfreefirmware|g" /etc/apt/sources.list
		fi
	done < /etc/apt/sources.list
	$_SUPERUSER sed -i 's/nonfreefirmware/non-free-firmware/g'  /etc/apt/sources.list
}

enable_repo_nonfree(){
	show_sm "enable_repo_nonfree"
	while IFS= read -r line;do
		if echo "${line}" | grep -E "^(deb|deb-src) (${mirror}|${mirror_security})" | grep -qv "non-free[[:blank:]]";then
			$_SUPERUSER sed -i "s|^${line}$|${line} nonfreeonly|g" /etc/apt/sources.list
		fi
	done < /etc/apt/sources.list
	$_SUPERUSER sed -i 's/nonfreeonly/non-free/g'  /etc/apt/sources.list
}

enable_nvidia_gpu_repo(){
	if [ ! -f "/usr/share/keyrings/nvidia-drivers.gpg" ];then
		show_sm "add nvidia-drivers keyrings"
		get_url_content "https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/3bf863cc.pub" | $_SUPERUSER gpg --dearmor | $_SUPERUSER tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
	fi
				
	if [ ! -f "/etc/apt/sources.list.d/nvidia-drivers.list" ];then
		show_sm "add nvidia-drivers repo"
		echo "deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/$distro_name_and_ver_/x86_64/ /" | $_SUPERUSER tee /etc/apt/sources.list.d/nvidia-drivers.list > /dev/null 2>&1
	fi
}

enable_repo_(){
	update_now=false
	if [ "$enable_contrib" = true ];then
		enable_repo_contrib && update_now=true
	fi
	
	if [ "$enable_nonfree_firmware" = true ];then
		enable_repo_nonfree_firmware && update_now=true
	fi
	
	if [ "$enable_nonfree" = true ];then
		enable_repo_nonfree && update_now=true
	fi
	
	if [ "${enable_nvidia_repo}" = "true" ];then
		enable_nvidia_gpu_repo
	fi

	if [ "$distro_name_" = "ubuntu" ];then
		show_sm "enable  universe  multiverse repo"
		$_SUPERUSER apt-get install -y software-properties-common
		$_SUPERUSER add-apt-repository -y universe
		$_SUPERUSER add-apt-repository -y multiverse
	fi
		
	if [ "$update_now" = true ];then
		aptupdate
	fi
}

##################################
# for rest
##################################

install_lightdm_now(){
	[ -f "${installer_phases}/install_lightdm_now" ] && return
	
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	show_im "installing ( lightdm )."
	
	if [ -f "/etc/X11/default-display-manager" ];then
		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
		[ "$d_d_m" != "lightdm"  ] && lightdm_does_not_exist=true
	else
		lightdm_does_not_exist=true
	fi
	
	if [ "$lightdm_does_not_exist" = true  ];then
		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_} && kill_package_ apt-get) || \
		($_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_} && kill_package_ apt-get) || \
		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get install -yq ${install_lightdm_} || (show_em "failed to install lightdm")
		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1 || (show_em "failed to change default-display-manager")
		$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true dpkg-reconfigure lightdm || (show_em "failed to dpkg-reconfigure lightdm")
	else
		show_im "lightdm already exist."
	fi
	touch "${installer_phases}/install_lightdm_now"
}

create_package_list(){
	# create list_of_apps file
	if [ ! -f "${list_of_apps_file_path}" ];then
		show_im "create_list_of_apps"
		apt list 2>/dev/null > "${list_of_apps_file_path}" 
	fi
}

install_packages(){
	if [ -z "${List_of_apt_2_install_}" ];then
    	($_SUPERUSER ${PACKAGER} install -yq ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
		($_SUPERUSER ${PACKAGER} install -yq ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
		$_SUPERUSER ${PACKAGER} install -yq ${List_of_apt_2_install_}
    else
    	show_im "List_of_apt_2_install_ are empty"
    	sleep 1
    fi
}

check_if_package_exist_in_repo(){
	package_name="${1-}"
	if [ "$package_name" = "--no-list-of-apps-file" ];then
		shift 1
		package_name="${1-}"
		if apt list --installed ${package_name} 2>/dev/null | grep "^${package_name}/" | grep -q "[installed]";then
			return 0
		else
			return 1
		fi
	else
		if ! dpkg -s "${package_name}" > /dev/null 2>&1;then
			check_apps_in_cache="$(grep "^$package_name/" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				return 0
			fi
		fi
	fi
}

add_packages_2_install_list()
{
	localarray="$@"
	
	for INDEX in ${localarray}
	do
		if ! dpkg -s "${INDEX}" > /dev/null 2>&1;then
			check_apps_in_cache="$(grep "^$INDEX/" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_="$List_of_apt_2_install_ $INDEX"
				show_im "${INDEX} added to install apps" 
			else
				show_wm "${INDEX} does not exist." 
			fi
		fi
	done
}

upgrade_now()
{
	show_im "Run upgrade_now function"
	show_sm "Run upgrade" 
	$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -y upgrade
	show_sm "Run dist-upgrade" 
	$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -y dist-upgrade
	show_sm "Run full-upgrade" 
	$_SUPERUSER DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true apt-get -y full-upgrade
	show_im "end upgrade_now" 
}

remove_package_with_error2info()
{
	localarray="$@"
	for package in ${localarray}
	do
		if dpkg -s "${package}" >/dev/null 2>&1;then
			show_im "Purging ${package}."
			$_SUPERUSER apt-get purge -y "$package"
		fi
	done
}

remove_unnecessary_package_manager_stuff(){
	show_im "removing apt-fast and conf"
	[ "$remove_aria2" = true ] && show_sm "removing aria2 package" && $_SUPERUSER apt-get purge -y aria2
	[ -f /usr/local/bin/apt-fast ] && show_sm "removing apt-fast" && $_SUPERUSER rm -f /usr/local/bin/apt-fast
	[ -f /etc/apt-fast.conf ] && show_sm "removing apt-fast.conf" && $_SUPERUSER rm -f /etc/apt-fast.conf
}

run_package_manager_autoclean(){
	show_im "autoremove unwanted pakages"
	$_SUPERUSER apt-get autoremove -y
	$_SUPERUSER apt-get autoclean -y
}

_unattended_upgrades_()
{
	auto_upgrades_file="/etc/apt/apt.conf.d/20auto-upgrades"
	if [ -f "${auto_upgrades_file}" ];then
		auto_upgrades_file_bak="/etc/apt/apt.conf.d/20auto-upgrades.bak"
		case "$1" in
			start)
				[ -f "${installer_phases}/_unattended_upgrades_start" ] && return
				show_im "start unattended upgrades."
				init_manager stop unattended-upgrades || :
				if [ ! -f "${auto_upgrades_file_bak}" ];then
					my-superuser mv "${auto_upgrades_file}" "${auto_upgrades_file_bak}"
				fi
				touch "${installer_phases}/_unattended_upgrades_start"
			;;
			stop)
				[ -f "${installer_phases}/_unattended_upgrades_stop" ] && return
				show_im "stop unattended upgrades."
				if [ -f "${auto_upgrades_file}" ] && [ -f "${auto_upgrades_file_bak}" ];then
					my-superuser rm "${auto_upgrades_file}"
				fi
					
				if [ -f "${auto_upgrades_file_bak}" ];then
					my-superuser mv "${auto_upgrades_file_bak}" "${auto_upgrades_file}"
				fi
				touch "${installer_phases}/_unattended_upgrades_stop"
			;;
		esac
	fi
}

switch_to_network_manager(){
	[ -f "${installer_phases}/switch_to_network_manager" ] && return
	[ -f "/etc/network/interfaces.old" ] && return
	show_m "runing switch_to_network_manager."
	network_manager_name="network-manager"
	show_im "switching to ${network_manager_name}"
	add_packages_2_install_list "${network_manager_name}"
	install_packages
	show_im "create to interfaces file"
	my-superuser tee "${temp_path}"/interfaces <<- 'EOF' >/dev/null
	# This file describes the network interfaces available on your system
	# and how to activate them. For more information, see interfaces(5).
		
	source /etc/network/interfaces.d/*
		
	# The loopback network interface
	auto lo
	iface lo inet loopback
	EOF
	my-superuser chmod 644 "${temp_path}"/interfaces
	show_im "create backup of interfaces file"
	[ -f "/etc/network/interfaces" ] && my-superuser mv /etc/network/interfaces /etc/network/interfaces.old
	my-superuser mkdir -p "/etc/network"
	my-superuser mv "${temp_path}"/interfaces /etc/network/interfaces
	show_im "Disable NetworkManager"
	my-superuser sed -i 's/managed=.*/managed=false/g' /etc/NetworkManager/NetworkManager.conf
	install_extra_Network_tools="rfkill"
	show_im "installing ${install_extra_Network_tools}"
	add_packages_2_install_list "${install_extra_Network_tools}"
	install_packages
	touch "${installer_phases}/switch_to_network_manager"
}

pre_package_manager_(){
	kill_package_ apt-get
	kill_package_ apt
	init_manager stop apt-daily.timer
	init_manager stop apt-daily-upgrade.timer
	aptfixer
	enable_repo_
	install_apt_fast || :
	
	if command -v apt-get >/dev/null 2>&1;then
		PACKAGER="apt-get"
	elif command -v apt-fast >/dev/null 2>&1;then
		PACKAGER="apt-fast"
	fi
	upgrade_now
	create_package_list
}
