#!/bin/sh
set -e

##################################
# for rest
##################################

create_package_list(){
	# create list_of_apps file
	if [ ! -f "${list_of_apps_file_path}" ];then
		show_im "Creating package list..."
		${PACKAGER} list 2>/dev/null > "${list_of_apps_file_path}"
	fi
	
	if [ ! -f "${list_of_installed_apps_file_path}" ];then
		show_im "Creating installed package list..."
		rpm -qa 2>/dev/null > "${list_of_installed_apps_file_path}" 
	fi
}

install_packages(){
	if [ -n "${List_of_apt_2_install_}" ];then
    	($_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
		($_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
		$_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_}
    else
    	show_wm "List_of_apt_2_install_ are empty"
    	sleep 1
    fi
}

check_if_package_exist_in_repo(){
	package_name="${1-}"
	if [ "$package_name" = "--no-list-of-apps-file" ];then
		shift 1
		package_name="${1-}"
		if dnf list ${package_name} 2>/dev/null | grep -q "^${package_name}";then
			return 0
		else
			return 1
		fi
	else
		if ! rpm -q "${package_name}" > /dev/null 2>&1;then
			check_apps_in_cache="$(grep "^$package_name" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				return 0
			fi
		fi
	fi
}

add_packages_2_install_list()
{
	localarray="$@"
	
	for INDEX in ${localarray}
	do
		if ! rpm -q "${INDEX}" > /dev/null 2>&1;then
			check_apps_in_cache="$(grep "^$INDEX" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_="$List_of_apt_2_install_ $INDEX"
				show_im "${INDEX} added to install apps" 
			else
				show_wm "${INDEX} does not exist." 
			fi
		fi
	done
}

upgrade_now()
{
	$_SUPERUSER ${PACKAGER} upgrade -y
	$_SUPERUSER ${PACKAGER} update -y
}

remove_package_with_error2info()
{
	packages="$@"
	if [ -n "$packages" ];then
		show_im "Removing ${packages}."
		$_SUPERUSER ${PACKAGER} remove -y "$package"
	else
		show_wm "no packages to remove."
	fi
}

remove_unnecessary_package_manager_stuff(){
	:
}

run_autoclean(){
	show_im "run autoremove autoclean."
	$_SUPERUSER dnf clean all
	$_SUPERUSER dnf autoremove -y
}

run_package_manager_autoclean(){
	show_im "autoremove unwanted pakages"
	run_autoclean       
    if [ -d /var/tmp ]; then
        my-superuser find /var/tmp -type f -atime +5 -delete
    fi
    if [ -d /tmp ]; then
        my-superuser find /tmp -type f -atime +5 -delete
    fi
    if [ -d /var/log ]; then
        my-superuser find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
    fi
	if [ "$init_system_are" = "systemd" ]; then
        my-superuser journalctl --vacuum-time=3d
    fi
}

_unattended_upgrades_()
{
	:
}

install_network_manager(){
	network_manager_name="NetworkManager-1"
	add_packages_2_install_list "${network_manager_name}"
}

install_lightdm_now(){
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	add_packages_2_install_list "${install_lightdm_}"
}

switch_to_network_manager(){
	[ -f "${installer_phases}/switch_to_network_manager" ] && return
	touch "${installer_phases}/switch_to_network_manager"
}

switch_lightdm_now(){
	[ -f "${installer_phases}/switch_lightdm_now" ] && return

	show_im "Switching to ( lightdm )."
	d_d_m="$(basename "$(readlink /etc/systemd/system/display-manager.service)")"
	if ! echo "$d_d_m" | grep -q "lightdm" ;then
		lightdm_does_not_exist=true
	fi
	
	if [ "$lightdm_does_not_exist" = true  ];then
		$_SUPERUSER systemctl disable $d_d_m
		$_SUPERUSER systemctl enable lightdm
	else
		show_im "lightdm already exist."
	fi
	touch "${installer_phases}/switch_lightdm_now"
}

enable_rpmfusion_repo(){
	$_SUPERUSER ${PACKAGER} install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
}

package_installed(){
	package="${1:-}"
	if grep -q "^$package" "$list_of_installed_apps_file_path";then
		return 0
	else
		return 1
	fi
}

removeSnaps(){
	[ -f "${installer_phases}/removeSnaps" ] && return
	command -v snap >/dev/null 2>&1 && my-superuser "$PACKAGER" remove -y snapd
	touch "${installer_phases}/removeSnaps"
}

pre_package_manager_(){
	[ -f "${installer_phases}/pre_package_manager_" ] && return
	kill_package_ ${PACKAGER}
	upgrade_now
	#enable_rpmfusion_repo
	touch "${installer_phases}/pre_package_manager_"
}
