#!/bin/sh
set -e

##################################
# only for ${PACKAGER}
##################################
if [ -z "$PACKAGER" ];then
	PACKAGER="pacman"
else
	if command_exist yay; then
        PACKAGER="yay"
    fi
fi

install_AUR_helper(){
	[ -f "${installer_phases}/install_AUR_helper" ] && return
	$_SUPERUSER true
    if ! command_exist yay && ! command_exist paru; then
    	$_SUPERUSER ${PACKAGER} --noconfirm -Syu
    	for package in yay yay-bin yay-git;do
    		pacman -Ss $package >/dev/null 2>&1 && yay_package_name="$package"
    		break
    	done
        if [ -n "$yay_package_name" ];then
        	show_im "Installing yay as AUR helper..."
        	$_SUPERUSER pacman --noconfirm -Syu $yay_package_name
        else
        	show_im "building yay from source..."
        	$_SUPERUSER pacman -S --needed git base-devel
        	cd /tmp
        	git clone https://aur.archlinux.org/yay-bin.git
        	chmod -R 700 yay-bin
			cd yay-bin
			makepkg -si
        fi
    else
    	${PACKAGER} --noconfirm -Syu
    fi
    
    if command_exist yay; then
    	show_sm "swtiching to yay..."
        PACKAGER="yay"
    elif command_exist paru; then
    	show_sm "swtiching to paru..."
        PACKAGER="paru"
    fi
    
    show_sm "updating rate-mirrors..."
    ${PACKAGER} --noconfirm -S rate-mirrors-bin
    $_SUPERUSER cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    $_SUPERUSER rate-mirrors --top-mirrors-number-to-retest=5 --disable-comments --save /etc/pacman.d/mirrorlist --allow-root arch
	touch "${installer_phases}/install_AUR_helper"
}

create_package_list(){
    if [ ! -f "${list_of_apps_file_path}" ]; then
        show_im "Creating package list..."
        ${PACKAGER} -Qq > "${list_of_apps_file_path}"
    fi
    
    if [ ! -f "${list_of_installed_apps_file_path}" ];then
		show_im "Creating installed package list..."
		${PACKAGER} -Q 2>/dev/null > "${list_of_installed_apps_file_path}" 
	fi
}

install_packages(){
	if [ -n "${List_of_apt_2_install_}" ];then
    	${PACKAGER} --noconfirm -Syu ${List_of_apt_2_install_}
    else
    	show_wm "List_of_apt_2_install_ are empty"
    	sleep 1
    fi
}

check_if_package_exist_in_repo(){
    package_name="$1"
    
}

check_if_package_exist_in_repo(){
	package_name="${1-}"
	if [ "$package_name" = "--no-list-of-apps-file" ];then
		shift 1
		package_name="${1-}"
		if ${PACKAGER} -Q "$package_name" >/dev/null 2>&1; then
			return 0
		else
			return 1
		fi
	else
		if ! ${PACKAGER} -Q "$package_name" >/dev/null 2>&1; then
			check_apps_in_cache="$(grep "^$package_name" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				return 0
			fi
		fi
	fi
}
add_packages_2_install_list(){
    for package in "$@"; do
        if ! ${PACKAGER} -Q "$package" >/dev/null 2>&1; then
            List_of_apt_2_install_="$List_of_apt_2_install_ $package"
            echo "$package added to install list."
        fi
    done
}

upgrade_now(){
	${PACKAGER} --noconfirm -Sy archlinux-keyring
    ${PACKAGER} -Syu --noconfirm
}

remove_package_with_error2info()
{
	packages="$@"
	if [ -n "$packages" ];then
		show_im "Removing ${packages}."
		${PACKAGER} -Rns --noconfirm "$package"
	else
		show_wm "no packages to remove."
	fi
}

remove_unnecessary_package_manager_stuff(){
	:
}

run_autoclean(){
	show_im "run autoremove autoclean."
	${PACKAGER} -Sc --noconfirm
	${PACKAGER} -Rns "$(pacman -Qtdq)" --noconfirm > /dev/null || true
}

run_package_manager_autoclean(){
	show_im "autoremove unwanted pakages"
	run_autoclean            
    if [ -d /var/tmp ]; then
        my-superuser find /var/tmp -type f -atime +5 -delete
    fi
    if [ -d /tmp ]; then
        my-superuser find /tmp -type f -atime +5 -delete
    fi
    if [ -d /var/log ]; then
        my-superuser find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
    fi
	if [ "$init_system_are" = "systemd" ]; then
        my-superuser journalctl --vacuum-time=3d
    fi
}

_unattended_upgrades_()
{
	:
}

install_network_manager(){
	network_manager_name="networkmanager"
	add_packages_2_install_list "${network_manager_name}"
}

install_lightdm_now(){
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	add_packages_2_install_list "${install_lightdm_}"
}

switch_to_network_manager(){
	[ -f "${installer_phases}/switch_to_network_manager" ] && return
	touch "${installer_phases}/switch_to_network_manager"
}

switch_lightdm_now(){
	[ -f "${installer_phases}/switch_lightdm_now" ] && return
    show_im "Switching to lightdm..."
    
    if [ -f "/etc/X11/default-display-manager" ]; then
        d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
        [ "$d_d_m" != "lightdm" ] && lightdm_does_not_exist=true
    else
        lightdm_does_not_exist=true
    fi
    
    if [ "$lightdm_does_not_exist" = true ]; then
        echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1
        $_SUPERUSER systemctl enable lightdm
    else
        show_sm "LightDM already exists."
    fi
    touch "${installer_phases}/switch_lightdm_now"
}

package_installed(){
	package="${1:-}"
	if grep -q "^$package" "$list_of_installed_apps_file_path";then
		return 0
	else
		return 1
	fi
}

removeSnaps(){
	[ -f "${installer_phases}/removeSnaps" ] && return
	command -v snap >/dev/null 2>&1 && "$PACKAGER" -Rns snapd --noconfirm
	touch "${installer_phases}/removeSnaps"
}

pre_package_manager_(){
	[ -f "${installer_phases}/pre_package_manager_" ] && return
    install_AUR_helper
    upgrade_now
    touch "${installer_phases}/pre_package_manager_"
}
