#!/bin/sh
set -e

##################################
# only for ${PACKAGER}
##################################
PACKAGER="pacman"

install_AUR_helper(){
    if ! command -v yay >/dev/null && ! command -v paru >/dev/null; then
        echo "Installing yay as AUR helper..."
        $_SUPERUSER ${PACKAGER} --noconfirm -S base-devel git
        cd /opt && $_SUPERUSER git clone https://aur.archlinux.org/yay-git.git && $_SUPERUSER chown -R ${USER}:${USER} ./yay-git
        cd yay-git && makepkg --noconfirm -si
    fi
    
    if command -v yay >/dev/null; then
        PACKAGER="yay"
    elif command -v paru >/dev/null; then
        PACKAGER="paru"
    fi
    
    ${PACKAGER} --noconfirm -S rate-mirrors-bin
    $_SUPERUSER cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    $_SUPERUSER rate-mirrors --top-mirrors-number-to-retest=5 --disable-comments --save /etc/pacman.d/mirrorlist --allow-root arch
}

install_lightdm_now(){
    [ -f "${installer_phases}/install_lightdm_now" ] && return
    
    install_lightdm_="lightdm lightdm-gtk-greeter-settings"
    echo "Installing lightdm..."
    
    if [ -f "/etc/X11/default-display-manager" ]; then
        d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
        [ "$d_d_m" != "lightdm" ] && lightdm_does_not_exist=true
    else
        lightdm_does_not_exist=true
    fi
    
    if [ "$lightdm_does_not_exist" = true ]; then
        echo "Installing ${install_lightdm_}..."
        ${PACKAGER} --noconfirm -S ${install_lightdm_}
        echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1
        $_SUPERUSER systemctl enable lightdm
    else
        echo "LightDM already exists."
    fi
    touch "${installer_phases}/install_lightdm_now"
}

create_package_list(){
    if [ ! -f "${list_of_apps_file_path}" ]; then
        echo "Creating package list..."
        ${PACKAGER} -Qq > "${list_of_apps_file_path}"
    fi
}

install_packages(){
    ${PACKAGER} --noconfirm -Syu ${List_of_apt_2_install_}
}

check_if_package_exist_in_repo(){
    package_name="$1"
    
}
check_if_package_exist_in_repo(){
	package_name="${1-}"
	if [ "$package_name" = "--no-list-of-apps-file" ];then
		shift 1
		package_name="${1-}"
		if ${PACKAGER} -Q "$package_name" >/dev/null 2>&1; then
			return 0
		else
			return 1
		fi
	else
		if ! ${PACKAGER} -Q "$package_name" >/dev/null 2>&1; then
			check_apps_in_cache="$(grep "^$package_name" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				return 0
			fi
		fi
	fi
}
add_packages_2_install_list(){
    for package in "$@"; do
        if ! ${PACKAGER} -Q "$package" >/dev/null 2>&1; then
            List_of_apt_2_install_="$List_of_apt_2_install_ $package"
            echo "$package added to install list."
        fi
    done
}

upgrade_now(){
	${PACKAGER} --noconfirm -Sy archlinux-keyring
    ${PACKAGER} -Syu --noconfirm
}

remove_package_with_error2info(){
    for package in "$@"; do
        if ${PACKAGER} -Q "$package" >/dev/null 2>&1; then
            echo "Removing $package."
            ${PACKAGER} -Rns --noconfirm "$package"
        fi
    done
}

remove_unnecessary_package_manager_stuff(){
	:
}

run_package_manager_autoclean(){
	:
}

_unattended_upgrades_()
{
	:
}

pre_package_manager_(){
    install_AUR_helper
    upgrade_now
    create_package_list
}
