#!/bin/sh
set -e

##################################
# for rest
##################################

install_lightdm_now(){
	[ -f "${installer_phases}/install_lightdm_now" ] && return
	
	install_lightdm_="lightdm lightdm-gtk-greeter-settings"
	show_im "installing ( lightdm )."
	if [ -f "/etc/X11/default-display-manager" ];then
		d_d_m="$(basename "$(cat /etc/X11/default-display-manager)")"
		[ "$d_d_m" != "lightdm"  ] && lightdm_does_not_exist=true
	else
		lightdm_does_not_exist=true
	fi
	
	if [ "$lightdm_does_not_exist" = true  ];then
		show_im "Install ${install_lightdm_} ."
		add_packages_2_install_list "${install_lightdm_}"
		kill_package_ ${PACKAGER} && install_packages || (kill_package_ ${PACKAGER} && install_packages) || (show_em "failed to install lightdm")
		echo "/usr/sbin/lightdm" | $_SUPERUSER tee /etc/X11/default-display-manager > /dev/null 2>&1
	else
		show_im "lightdm already exist."
	fi
	touch "${installer_phases}/install_lightdm_now"
}

create_package_list(){
	# create list_of_apps file
	if [ ! -f "${list_of_apps_file_path}" ];then
		show_im "create_list_of_apps"
		$_SUPERUSER ${PACKAGER} se -r udp 2>/dev/null > "${list_of_apps_file_path}" 
	fi
}

install_packages(){
	if [ -z "${List_of_apt_2_install_}" ];then
    	($_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
		($_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_} && kill_package_ ${PACKAGER}) || \
		$_SUPERUSER ${PACKAGER} install -y ${List_of_apt_2_install_}
    else
    	show_wm "List_of_apt_2_install_ are empty"
    	sleep 1
    fi
}

check_if_package_exist_in_repo(){
	package_name="${1-}"
	if [ "$package_name" = "--no-list-of-apps-file" ];then
		shift 1
		package_name="${1-}"
		if rpm -q "${package_name}" > /dev/null 2>&1; then
			return 0
		else
			return 1
		fi
	else
		if ! rpm -q "${package_name}" > /dev/null 2>&1; then
			check_apps_in_cache="$(grep "^$package_name" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				return 0
			fi
		fi
	fi
}

add_packages_2_install_list()
{
	localarray="$@"
	
	for INDEX in ${localarray}
	do
		if ! rpm -q "${INDEX}" > /dev/null 2>&1;then
			check_apps_in_cache="$(grep "^$INDEX" "${list_of_apps_file_path}" 2>/dev/null || :)"
			if [ -n "${check_apps_in_cache}" ];then
				List_of_apt_2_install_="$List_of_apt_2_install_ $INDEX"
				show_im "${INDEX} added to install apps" 
			else
				show_wm "${INDEX} does not exist." 
			fi
		fi
	done
}
	
upgrade_now()
{
	$_SUPERUSER ${PACKAGER} refresh
	$_SUPERUSER ${PACKAGER} update -y
}

remove_package_with_error2info()
{
	localarray="$@"
	for package in ${localarray}
	do
		if rpm -q "${package}" >/dev/null 2>&1; then
			show_im "Removing ${package}."
			$_SUPERUSER ${PACKAGER} remove -y "$package"
		fi
	done
}

remove_unnecessary_package_manager_stuff(){
	:
}

run_package_manager_autoclean(){
	$_SUPERUSER ${PACKAGER} clean --all
}

_unattended_upgrades_()
{
	case "$1" in
		start)
			[ -f "${installer_phases}/_unattended_upgrades_start" ] && return
			show_im "Starting unattended upgrades (zypper cron setup needed)."
			$_SUPERUSER systemctl enable --now packagekit-background.timer
			touch "${installer_phases}/_unattended_upgrades_start"
		;;
		stop)
			[ -f "${installer_phases}/_unattended_upgrades_stop" ] && return
			show_im "Stopping unattended upgrades."
			$_SUPERUSER systemctl disable --now packagekit-background.timer
			touch "${installer_phases}/_unattended_upgrades_stop"
		;;
	esac
}

switch_to_network_manager(){
	[ -f "${installer_phases}/switch_to_network_manager" ] && return
	touch "${installer_phases}/switch_to_network_manager"
}

pre_package_manager_(){
	kill_package_ ${PACKAGER}
	upgrade_now
	create_package_list
}
