#!/bin/sh

set -e

if virsh net-info network.xml >/dev/null 2>/dev/null; then
	echo "Libvirt network torvirt already exists."
else
	virsh net-define network.xml
fi

output=$(podman image ls -q -f reference=$IMG_NAME)

if [ "$output" ]; then
	echo "OCI image torvirt already exists"
else
	cd gateway && podman build -t torvirt .
fi
