#!/bin/sh	
#must have apps
install_core_apps="arandr autorandr"
install_ufw_apps="ufw"
install_X11_apps="x11-utils xorg xserver-xorg-input-all xinput dbus-x11 xinit xdg-user-dirs x11-xserver-utils xclip xwallpaper"
install_must_have_apps="jq cbatticon xprintidle yad git rofi picom mlocate htop unzip dunst libnotify-bin"
install_must_have_apps2="psmisc gparted inxi s-tui dfc hwinfo synaptic galternatives xdotool acl lm-sensors ntfs-3g"
install_openbox_="openbox obconf xcape tint2"
install_audio_tray_app="pnmixer"
install_image_viewer_apps="viewnior"
install_files_manager_support_app="gvfs gvfs-fuse gvfs-backends file-roller baobab"
install_terminal="kitty"
install_conky_all_app="conky-all"
install_if_laptop="tlp tlp-rdw powertop xserver-xorg-input-synaptics"
install_cli_sound_app="mpd mpc ncmpcpp"
install_MIDI_sound_app="wildmidi timidity"
install_text_editer_app="geany zathura"
install_mediaplayer_app="mpv"
install_x_lock_extra="i3lock i3lock-fancy"
install_fonts="fonts-noto fonts-droid-fallback fonts-cantarell fonts-liberation fonts-opensymbol fonts-noto-core fonts-noto-mono fonts-inconsolata"
install_themes="papirus-icon-theme fonts-noto-color-emoji fonts-firacode fonts-font-awesome arc-theme gtk3-nocsd numix-icon-theme paper-icon-theme dmz-cursor-theme"
install_themes_tools="xsettingsd lxappearance"
install_polkit_apps="policykit-1 policykit-1-gnome gnome-keyring"

#firefox
install_firefox_="firefox-esr"

# slop for ac-shots and screen recoding , ffmpeg for screen recoding , at for bl-beepmein , wmctrl for style-manager and files-uploader
install_for_scripts="slop ffmpeg at wmctrl"

#######################
## extra apps
#######################
install_clipman_manager="diodon"
install_files_manager_thunar="thunar thunar-archive-plugin"
install_files_manager_pcmanfm="pcmanfm"
install_xfce4_panel="xfce4-panel xfce4-settings xfce4-whiskermenu-plugin network-manager-gnome"
install_polybar="polybar libnm-dev"
install_qt5ct="qt5ct qt5-style-kvantum libqt5svg5 qml-module-qtquick-controls"
install_jgmenu="jgmenu"
install_bspwm="bspwm sxhkd"
install_zsh="zsh"
#######################
## better bash
#######################
install_better_bash="bash bash-completion"

#######################
## better shell
#######################
install_better_shell="tar bat fzf trash-cli command-not-found thefuck highlight lf"

#######################
## extra
#######################
install_extra_apps="micro multitail ncdu tree nitrogen nsxiv dos2unix meld btop"
