#!/bin/sh
disto_specific_Drivers_installer(){
	show_im "Configer Disto Specific Drivers."
	if [ "$this_is_laptop" = true ];then
		show_im "this is laptop"
	fi
	touch "${installer_phases}/disto_specific_Drivers_installer"
}
