greeter_background="/usr/share/my_stuff/my_wallpapers/owl4ce_wall-03.jpg"
greeter_theme_name="Sweetly"
greeter_icon_theme_name="Papirus-Custom"
greeter_font_name="Cantarell 9"
greeter_position="57%,start 22%,start"
