#!/bin/sh
disto_specific_apps_installer(){
	[ -f "${installer_phases}/disto_specific_apps_installer" ] && return
		
	service_manager enable dbus.service
	service_manager enable avahi-daemon
	
	pkgfile --update
	touch "${installer_phases}/disto_specific_apps_installer"
}
