#!/bin/sh
create_to_be_purged_list(){
	[ -f "${installer_phases}/create_to_be_purged_list" ] && return
		package_installed snapd && show_sm "adding snap package to remove list" && snap="snapd" || snap=""
		_purge_it=""
		to_be_purged="xterm ${install_autoinstall_firmware} ${snap}"
		for package in ${to_be_purged};do
			if package_installed "$package";then
				_purge_it="$_purge_it $package"
			else
				show_wm_only "$package does not exist"
			fi
		done
		echo "_purge_it=\"$_purge_it\"" >> "${save_value_file}"
	touch "${installer_phases}/create_to_be_purged_list"
}

purge_some_unnecessary_pakages(){
	[ -f "${installer_phases}/purge_some_unnecessary_pakages" ] && return
	show_m "purge some unnecessary pakages"
	create_to_be_purged_list
	if [ "$run_purge_some_unnecessary_pakages" = "Y" ];then
		show_im "purging apps"
		remove_packages "${_purge_it}"
	fi
	run_autoclean
	touch "${installer_phases}/purge_some_unnecessary_pakages"
}

disable_some_unnecessary_services(){
	[ -f "${installer_phases}/disable_some_unnecessary_services" ] && return
	touch "${installer_phases}/disable_some_unnecessary_services"
}
