#!/usr/bin/env sh
set -e
#ffmpegthumbnailer

owl4ce_dotfile_temp_path="/tmp/owl4ce_dotfile"

[ -d "${owl4ce_dotfile_temp_path}" ] && rm -rdf "${owl4ce_dotfile_temp_path}"
[ -d "/usr/share/my_stuff" ] && sudo rm -rdf "/usr/share/my_stuff"

sudo mkdir -p /usr/share/my_stuff/icons
sudo cp -rf $HOME/Desktop/my_stuff/icons/eyecandy /usr/share/my_stuff/icons

sudo mkdir -p /usr/share/my_stuff/lib/common
sudo cp -rf $HOME/Desktop/my_stuff/lib/common/WM /usr/share/my_stuff/lib/common

sudo mkdir -p /usr/share/my_stuff/bin/not_add_2_path
sudo cp -rf "$HOME/Desktop/my_stuff/bin/not_add_2_path/owl4ce" /usr/share/my_stuff/bin/not_add_2_path
sudo cp -rf "$HOME/Desktop/my_stuff/bin/not_add_2_path/tint2" /usr/share/my_stuff/bin/not_add_2_path
sudo cp -rf "$HOME/Desktop/my_stuff/bin/not_add_2_path/dunst" /usr/share/my_stuff/bin/not_add_2_path

sudo mkdir -p /usr/share/my_stuff/system_files/bin
cd /usr/share/my_stuff/system_files/bin
sudo cp -rf "$HOME/Desktop/my_stuff/bin/bin/cal-popup" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/openbox/obamenu.py" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/session_managers/dunst-session" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/session_managers/tint2-session" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/WM/kill_process.sh" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/WM/my_session_manager" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/bin/my-shots" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/pipemenu/randr-pipemenu" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/WM/reload_gtk23" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/tint2/tint2_scripts" .
sudo cp -rf "$HOME/Desktop/my_stuff/bin/must_create_script/popup_terminal/kitty" popup_terminal

sudo cp -rf "$HOME/Desktop/my_stuff/bin/apps/ncmpcpp_launcher" .

sudo ln -sf /usr/bin/thunar /usr/share/my_stuff/system_files/bin/my-file-manager
sudo ln -sf /usr/bin/kitty /usr/share/my_stuff/system_files/bin/my-terminal-emulator

cd "$HOME/Desktop/my_stuff/bin/must_create_script/volume_cli_control"
sudo ./make

####################################

mkdir -p "${owl4ce_dotfile_temp_path}"
cd "${owl4ce_dotfile_temp_path}"

mkdir -p .config/blob/tint2/
cp -rf $HOME/Desktop/my_stuff/blob/tint2/owl4ce_dark .config/blob/tint2
cp -rf $HOME/Desktop/my_stuff/blob_extra/tint2/owl4ce_dark/* .config/blob/tint2/owl4ce_dark

cp -rf $HOME/Desktop/my_stuff/blob/tint2/owl4ce_light .config/blob/tint2
cp -rf $HOME/Desktop/my_stuff/blob_extra/tint2/owl4ce_light/* .config/blob/tint2/owl4ce_light

mkdir -p .config/tint2/
cp -rf $HOME/Desktop/my_stuff/skel_extra/.config/tint2/owl4ce_dark .config/tint2/
cp -rf $HOME/Desktop/my_stuff/skel_extra/.config/tint2/owl4ce_light .config/tint2/

cp -rf $HOME/Desktop/my_stuff/skel/.config/scriptconfig .config
cp -rf $HOME/Desktop/my_stuff/skel/.config/kitty .config
cp -rf $HOME/Desktop/my_stuff/skel/.config/mpd .config
cp -rf $HOME/Desktop/my_stuff/skel/.config/mpv .config
sed -i 's/vo=gpu/#vo=gpu/g' .config/mpv/mpv.conf
cp -rf $HOME/Desktop/my_stuff/skel/.config/ncmpcpp .config
cp -rf $HOME/Desktop/my_stuff/skel_extra/.config/geany .config
cp -rf $HOME/Desktop/my_stuff/skel_extra/.config/xfce4 .config
cp -rf $HOME/Desktop/my_stuff/skel/.config/htop .config
cp -rf $HOME/Desktop/my_stuff/skel_extra/.config/parcellite .config
cp -rf $HOME/Desktop/my_stuff/skel_extra/.config/Thunar .config
cp -rf $HOME/Desktop/my_stuff/skel/.config/rofi .config
cp -rf $HOME/Desktop/my_stuff/skel/.config/dunst .config
cp -rf .config/blob/tint2/owl4ce_dark/config/* .config/
cat .config/dunst/global .config/dunst/theme.dunstrc > ".config/dunst/dunstrc" 

mkdir -p .config/openbox/Menu
cp -rf /etc/xdg/openbox/rc.xml .config/openbox
sed -i 's|</applications>|<application class="*" type="normal">\n  <decor>yes</decor>\n</application>\n</applications>|' .config/openbox/rc.xml
sed -i 's|<name>desktop||g' .config/openbox/rc.xml
cp -rf $HOME/Desktop/my_stuff/skel/.config/openbox/Menu/owl4ce.xml .config/openbox/Menu

cat << 'EOF' > .config/openbox/autostart.sh
#!/usr/bin/env sh
trays_apps="mpd nm-applet xfce4-power-manager diodon"

. "/usr/share/my_stuff/lib/common/WM"
. "${Distro_config_file}"

exec >/dev/null 2>&1

#{ pidof -s pulseaudio -q || pulseaudio --start --log-target=syslog; } &
killall -9 tint2 dunst -q

for TRAY in ${trays_apps};do
	pidof -s "${TRAY}" -q  && killall -9 ${TRAY} -q
done
                  
mkdir -p "/tmp/$USER"

dunst -config "$HOME/.config/dunst/dunstrc" &	

nitrogen --force-setter=xwindows --set-zoom-fill --save "${WALLPAPERS_DIR}/${CHK_WALLPAPER}"  &

tint2 -c "${HOME}${tint2_sessionfile}" &

sleep 2

for TRAY in ${trays_apps};do
	pidof -s "${TRAY}" -q  || ${TRAY} >/dev/null 2>&1 &
done

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
EOF
chmod +x .config/openbox/autostart.sh

cat << 'EOF' > .config/openbox/environment
export LESSHISTFILE='/dev/null'
export PATH="/usr/share/my_stuff/system_files/bin:$PATH"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
EOF

ln -sf $HOME/Desktop/Theme_Stuff/fonts .fonts
ln -sf $HOME/Desktop/Theme_Stuff/themes .themes
ln -sf $HOME/Desktop/my_stuff/icons/Joyful.OBB $HOME/Desktop/Theme_Stuff/themes

mkdir -p .icons
ln -sf $HOME/Desktop/Theme_Stuff/icons/Papirus-Custom .icons
ln -sf $HOME/Desktop/Theme_Stuff/icons/Papirus-Dark-Custom .icons

mkdir -p .wallpapers
ln -sf $HOME/Desktop/my_stuff/my_wallpapers/owl4ce_dark_wall-01.jpg .wallpapers
ln -sf $HOME/Desktop/my_stuff/my_wallpapers/owl4ce_dark_wall-02.jpg .wallpapers
ln -sf $HOME/Desktop/my_stuff/my_wallpapers/owl4ce_light_wall-01.jpg .wallpapers
ln -sf $HOME/Desktop/my_stuff/my_wallpapers/owl4ce_light_wall-02.jpg .wallpapers

mkdir -p .local/share/applications
ln -sf $HOME/Desktop/my_stuff/applications/ncmpcpp.desktop .local/share/applications
ln -sf $HOME/Desktop/my_stuff/applications/ncmpcpp.album-art.desktop .local/share/applications
ln -sf $HOME/Desktop/my_stuff/applications/ncmpcpp.single.album-art.desktop .local/share/applications

find "${owl4ce_dotfile_temp_path}" -type f -exec sed -i "s/MmdmdmdmdmdmdmdmdmM/$USER/g" {} +

cd $HOME
for d in .config .fonts .icons .local/share/applications .scripts .themes .urxvt .wallpapers scripts .gtkrc-2.0 .joyfuld .Xresources;do
	[ -d "$d" ] && rm -rdf "$d"
done

cp -rfa "${owl4ce_dotfile_temp_path}"/.??* $HOME

fc-cache -rv

sudo update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/bin/openbox-session 60

echo "done done done"

systemctl --user exit

























